// Code generated by go-swagger; DO NOT EDIT.

package s_a_m_l_roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateOrganizationSamlRoleReader is a Reader for the CreateOrganizationSamlRole structure.
type CreateOrganizationSamlRoleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateOrganizationSamlRoleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateOrganizationSamlRoleCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateOrganizationSamlRoleCreated creates a CreateOrganizationSamlRoleCreated with default headers values
func NewCreateOrganizationSamlRoleCreated() *CreateOrganizationSamlRoleCreated {
	return &CreateOrganizationSamlRoleCreated{}
}

/*CreateOrganizationSamlRoleCreated handles this case with default header values.

Successful operation
*/
type CreateOrganizationSamlRoleCreated struct {
	Payload interface{}
}

func (o *CreateOrganizationSamlRoleCreated) Error() string {
	return fmt.Sprintf("[POST /organizations/{organizationId}/samlRoles][%d] createOrganizationSamlRoleCreated  %+v", 201, o.Payload)
}

func (o *CreateOrganizationSamlRoleCreated) GetPayload() interface{} {
	return o.Payload
}

func (o *CreateOrganizationSamlRoleCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
