// Code generated by go-swagger; DO NOT EDIT.

package s_a_m_l_roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cisco-sso/meraki-cli/models"
)

// NewCreateOrganizationSamlRoleParams creates a new CreateOrganizationSamlRoleParams object
// with the default values initialized.
func NewCreateOrganizationSamlRoleParams() *CreateOrganizationSamlRoleParams {
	var ()
	return &CreateOrganizationSamlRoleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateOrganizationSamlRoleParamsWithTimeout creates a new CreateOrganizationSamlRoleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateOrganizationSamlRoleParamsWithTimeout(timeout time.Duration) *CreateOrganizationSamlRoleParams {
	var ()
	return &CreateOrganizationSamlRoleParams{

		timeout: timeout,
	}
}

// NewCreateOrganizationSamlRoleParamsWithContext creates a new CreateOrganizationSamlRoleParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateOrganizationSamlRoleParamsWithContext(ctx context.Context) *CreateOrganizationSamlRoleParams {
	var ()
	return &CreateOrganizationSamlRoleParams{

		Context: ctx,
	}
}

// NewCreateOrganizationSamlRoleParamsWithHTTPClient creates a new CreateOrganizationSamlRoleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateOrganizationSamlRoleParamsWithHTTPClient(client *http.Client) *CreateOrganizationSamlRoleParams {
	var ()
	return &CreateOrganizationSamlRoleParams{
		HTTPClient: client,
	}
}

/*CreateOrganizationSamlRoleParams contains all the parameters to send to the API endpoint
for the create organization saml role operation typically these are written to a http.Request
*/
type CreateOrganizationSamlRoleParams struct {

	/*CreateOrganizationSamlRole*/
	CreateOrganizationSamlRole *models.CreateOrganizationSamlRole
	/*OrganizationID*/
	OrganizationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create organization saml role params
func (o *CreateOrganizationSamlRoleParams) WithTimeout(timeout time.Duration) *CreateOrganizationSamlRoleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create organization saml role params
func (o *CreateOrganizationSamlRoleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create organization saml role params
func (o *CreateOrganizationSamlRoleParams) WithContext(ctx context.Context) *CreateOrganizationSamlRoleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create organization saml role params
func (o *CreateOrganizationSamlRoleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create organization saml role params
func (o *CreateOrganizationSamlRoleParams) WithHTTPClient(client *http.Client) *CreateOrganizationSamlRoleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create organization saml role params
func (o *CreateOrganizationSamlRoleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCreateOrganizationSamlRole adds the createOrganizationSamlRole to the create organization saml role params
func (o *CreateOrganizationSamlRoleParams) WithCreateOrganizationSamlRole(createOrganizationSamlRole *models.CreateOrganizationSamlRole) *CreateOrganizationSamlRoleParams {
	o.SetCreateOrganizationSamlRole(createOrganizationSamlRole)
	return o
}

// SetCreateOrganizationSamlRole adds the createOrganizationSamlRole to the create organization saml role params
func (o *CreateOrganizationSamlRoleParams) SetCreateOrganizationSamlRole(createOrganizationSamlRole *models.CreateOrganizationSamlRole) {
	o.CreateOrganizationSamlRole = createOrganizationSamlRole
}

// WithOrganizationID adds the organizationID to the create organization saml role params
func (o *CreateOrganizationSamlRoleParams) WithOrganizationID(organizationID string) *CreateOrganizationSamlRoleParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the create organization saml role params
func (o *CreateOrganizationSamlRoleParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateOrganizationSamlRoleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CreateOrganizationSamlRole != nil {
		if err := r.SetBodyParam(o.CreateOrganizationSamlRole); err != nil {
			return err
		}
	}

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
