// Code generated by go-swagger; DO NOT EDIT.

package m_x_warm_spare_settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetNetworkWarmSpareSettingsReader is a Reader for the GetNetworkWarmSpareSettings structure.
type GetNetworkWarmSpareSettingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNetworkWarmSpareSettingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNetworkWarmSpareSettingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetNetworkWarmSpareSettingsOK creates a GetNetworkWarmSpareSettingsOK with default headers values
func NewGetNetworkWarmSpareSettingsOK() *GetNetworkWarmSpareSettingsOK {
	return &GetNetworkWarmSpareSettingsOK{}
}

/*GetNetworkWarmSpareSettingsOK handles this case with default header values.

Successful operation
*/
type GetNetworkWarmSpareSettingsOK struct {
	Payload interface{}
}

func (o *GetNetworkWarmSpareSettingsOK) Error() string {
	return fmt.Sprintf("[GET /networks/{networkId}/warmSpareSettings][%d] getNetworkWarmSpareSettingsOK  %+v", 200, o.Payload)
}

func (o *GetNetworkWarmSpareSettingsOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetNetworkWarmSpareSettingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
