// Code generated by go-swagger; DO NOT EDIT.

package m_x_static_routes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateNetworkStaticRouteReader is a Reader for the CreateNetworkStaticRoute structure.
type CreateNetworkStaticRouteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateNetworkStaticRouteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateNetworkStaticRouteCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateNetworkStaticRouteCreated creates a CreateNetworkStaticRouteCreated with default headers values
func NewCreateNetworkStaticRouteCreated() *CreateNetworkStaticRouteCreated {
	return &CreateNetworkStaticRouteCreated{}
}

/*CreateNetworkStaticRouteCreated handles this case with default header values.

Successful operation
*/
type CreateNetworkStaticRouteCreated struct {
	Payload interface{}
}

func (o *CreateNetworkStaticRouteCreated) Error() string {
	return fmt.Sprintf("[POST /networks/{networkId}/staticRoutes][%d] createNetworkStaticRouteCreated  %+v", 201, o.Payload)
}

func (o *CreateNetworkStaticRouteCreated) GetPayload() interface{} {
	return o.Payload
}

func (o *CreateNetworkStaticRouteCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
