// Code generated by go-swagger; DO NOT EDIT.

package m_x_static_routes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetNetworkStaticRouteParams creates a new GetNetworkStaticRouteParams object
// with the default values initialized.
func NewGetNetworkStaticRouteParams() *GetNetworkStaticRouteParams {
	var ()
	return &GetNetworkStaticRouteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetNetworkStaticRouteParamsWithTimeout creates a new GetNetworkStaticRouteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetNetworkStaticRouteParamsWithTimeout(timeout time.Duration) *GetNetworkStaticRouteParams {
	var ()
	return &GetNetworkStaticRouteParams{

		timeout: timeout,
	}
}

// NewGetNetworkStaticRouteParamsWithContext creates a new GetNetworkStaticRouteParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetNetworkStaticRouteParamsWithContext(ctx context.Context) *GetNetworkStaticRouteParams {
	var ()
	return &GetNetworkStaticRouteParams{

		Context: ctx,
	}
}

// NewGetNetworkStaticRouteParamsWithHTTPClient creates a new GetNetworkStaticRouteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetNetworkStaticRouteParamsWithHTTPClient(client *http.Client) *GetNetworkStaticRouteParams {
	var ()
	return &GetNetworkStaticRouteParams{
		HTTPClient: client,
	}
}

/*GetNetworkStaticRouteParams contains all the parameters to send to the API endpoint
for the get network static route operation typically these are written to a http.Request
*/
type GetNetworkStaticRouteParams struct {

	/*NetworkID*/
	NetworkID string
	/*StaticRouteID*/
	StaticRouteID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get network static route params
func (o *GetNetworkStaticRouteParams) WithTimeout(timeout time.Duration) *GetNetworkStaticRouteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get network static route params
func (o *GetNetworkStaticRouteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get network static route params
func (o *GetNetworkStaticRouteParams) WithContext(ctx context.Context) *GetNetworkStaticRouteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get network static route params
func (o *GetNetworkStaticRouteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get network static route params
func (o *GetNetworkStaticRouteParams) WithHTTPClient(client *http.Client) *GetNetworkStaticRouteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get network static route params
func (o *GetNetworkStaticRouteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNetworkID adds the networkID to the get network static route params
func (o *GetNetworkStaticRouteParams) WithNetworkID(networkID string) *GetNetworkStaticRouteParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the get network static route params
func (o *GetNetworkStaticRouteParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WithStaticRouteID adds the staticRouteID to the get network static route params
func (o *GetNetworkStaticRouteParams) WithStaticRouteID(staticRouteID string) *GetNetworkStaticRouteParams {
	o.SetStaticRouteID(staticRouteID)
	return o
}

// SetStaticRouteID adds the staticRouteId to the get network static route params
func (o *GetNetworkStaticRouteParams) SetStaticRouteID(staticRouteID string) {
	o.StaticRouteID = staticRouteID
}

// WriteToRequest writes these params to a swagger request
func (o *GetNetworkStaticRouteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param networkId
	if err := r.SetPathParam("networkId", o.NetworkID); err != nil {
		return err
	}

	// path param staticRouteId
	if err := r.SetPathParam("staticRouteId", o.StaticRouteID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
