// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetOrganizationDevicesParams creates a new GetOrganizationDevicesParams object
// with the default values initialized.
func NewGetOrganizationDevicesParams() *GetOrganizationDevicesParams {
	var ()
	return &GetOrganizationDevicesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrganizationDevicesParamsWithTimeout creates a new GetOrganizationDevicesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOrganizationDevicesParamsWithTimeout(timeout time.Duration) *GetOrganizationDevicesParams {
	var ()
	return &GetOrganizationDevicesParams{

		timeout: timeout,
	}
}

// NewGetOrganizationDevicesParamsWithContext creates a new GetOrganizationDevicesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOrganizationDevicesParamsWithContext(ctx context.Context) *GetOrganizationDevicesParams {
	var ()
	return &GetOrganizationDevicesParams{

		Context: ctx,
	}
}

// NewGetOrganizationDevicesParamsWithHTTPClient creates a new GetOrganizationDevicesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOrganizationDevicesParamsWithHTTPClient(client *http.Client) *GetOrganizationDevicesParams {
	var ()
	return &GetOrganizationDevicesParams{
		HTTPClient: client,
	}
}

/*GetOrganizationDevicesParams contains all the parameters to send to the API endpoint
for the get organization devices operation typically these are written to a http.Request
*/
type GetOrganizationDevicesParams struct {

	/*ConfigurationUpdatedAfter
	  Filter results by whether or not the device's configuration has been updated after the given timestamp

	*/
	ConfigurationUpdatedAfter *string
	/*EndingBefore
	  A token used by the server to indicate the end of the page. Often this is a timestamp or an ID but it is not limited to those. This parameter should not be defined by client applications. The link for the first, last, prev, or next page in the HTTP Link header should define it.

	*/
	EndingBefore *string
	/*OrganizationID*/
	OrganizationID string
	/*PerPage
	  The number of entries per page returned. Acceptable range is 3 - 1000. Default is 1000.

	*/
	PerPage *int32
	/*StartingAfter
	  A token used by the server to indicate the start of the page. Often this is a timestamp or an ID but it is not limited to those. This parameter should not be defined by client applications. The link for the first, last, prev, or next page in the HTTP Link header should define it.

	*/
	StartingAfter *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get organization devices params
func (o *GetOrganizationDevicesParams) WithTimeout(timeout time.Duration) *GetOrganizationDevicesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get organization devices params
func (o *GetOrganizationDevicesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get organization devices params
func (o *GetOrganizationDevicesParams) WithContext(ctx context.Context) *GetOrganizationDevicesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get organization devices params
func (o *GetOrganizationDevicesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get organization devices params
func (o *GetOrganizationDevicesParams) WithHTTPClient(client *http.Client) *GetOrganizationDevicesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get organization devices params
func (o *GetOrganizationDevicesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConfigurationUpdatedAfter adds the configurationUpdatedAfter to the get organization devices params
func (o *GetOrganizationDevicesParams) WithConfigurationUpdatedAfter(configurationUpdatedAfter *string) *GetOrganizationDevicesParams {
	o.SetConfigurationUpdatedAfter(configurationUpdatedAfter)
	return o
}

// SetConfigurationUpdatedAfter adds the configurationUpdatedAfter to the get organization devices params
func (o *GetOrganizationDevicesParams) SetConfigurationUpdatedAfter(configurationUpdatedAfter *string) {
	o.ConfigurationUpdatedAfter = configurationUpdatedAfter
}

// WithEndingBefore adds the endingBefore to the get organization devices params
func (o *GetOrganizationDevicesParams) WithEndingBefore(endingBefore *string) *GetOrganizationDevicesParams {
	o.SetEndingBefore(endingBefore)
	return o
}

// SetEndingBefore adds the endingBefore to the get organization devices params
func (o *GetOrganizationDevicesParams) SetEndingBefore(endingBefore *string) {
	o.EndingBefore = endingBefore
}

// WithOrganizationID adds the organizationID to the get organization devices params
func (o *GetOrganizationDevicesParams) WithOrganizationID(organizationID string) *GetOrganizationDevicesParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the get organization devices params
func (o *GetOrganizationDevicesParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WithPerPage adds the perPage to the get organization devices params
func (o *GetOrganizationDevicesParams) WithPerPage(perPage *int32) *GetOrganizationDevicesParams {
	o.SetPerPage(perPage)
	return o
}

// SetPerPage adds the perPage to the get organization devices params
func (o *GetOrganizationDevicesParams) SetPerPage(perPage *int32) {
	o.PerPage = perPage
}

// WithStartingAfter adds the startingAfter to the get organization devices params
func (o *GetOrganizationDevicesParams) WithStartingAfter(startingAfter *string) *GetOrganizationDevicesParams {
	o.SetStartingAfter(startingAfter)
	return o
}

// SetStartingAfter adds the startingAfter to the get organization devices params
func (o *GetOrganizationDevicesParams) SetStartingAfter(startingAfter *string) {
	o.StartingAfter = startingAfter
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrganizationDevicesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ConfigurationUpdatedAfter != nil {

		// query param configurationUpdatedAfter
		var qrConfigurationUpdatedAfter string
		if o.ConfigurationUpdatedAfter != nil {
			qrConfigurationUpdatedAfter = *o.ConfigurationUpdatedAfter
		}
		qConfigurationUpdatedAfter := qrConfigurationUpdatedAfter
		if qConfigurationUpdatedAfter != "" {
			if err := r.SetQueryParam("configurationUpdatedAfter", qConfigurationUpdatedAfter); err != nil {
				return err
			}
		}

	}

	if o.EndingBefore != nil {

		// query param endingBefore
		var qrEndingBefore string
		if o.EndingBefore != nil {
			qrEndingBefore = *o.EndingBefore
		}
		qEndingBefore := qrEndingBefore
		if qEndingBefore != "" {
			if err := r.SetQueryParam("endingBefore", qEndingBefore); err != nil {
				return err
			}
		}

	}

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}

	if o.PerPage != nil {

		// query param perPage
		var qrPerPage int32
		if o.PerPage != nil {
			qrPerPage = *o.PerPage
		}
		qPerPage := swag.FormatInt32(qrPerPage)
		if qPerPage != "" {
			if err := r.SetQueryParam("perPage", qPerPage); err != nil {
				return err
			}
		}

	}

	if o.StartingAfter != nil {

		// query param startingAfter
		var qrStartingAfter string
		if o.StartingAfter != nil {
			qrStartingAfter = *o.StartingAfter
		}
		qStartingAfter := qrStartingAfter
		if qStartingAfter != "" {
			if err := r.SetQueryParam("startingAfter", qStartingAfter); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
