// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetOrganizationDevicesReader is a Reader for the GetOrganizationDevices structure.
type GetOrganizationDevicesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrganizationDevicesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOrganizationDevicesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetOrganizationDevicesOK creates a GetOrganizationDevicesOK with default headers values
func NewGetOrganizationDevicesOK() *GetOrganizationDevicesOK {
	return &GetOrganizationDevicesOK{}
}

/*GetOrganizationDevicesOK handles this case with default header values.

Successful operation
*/
type GetOrganizationDevicesOK struct {
	Payload interface{}
}

func (o *GetOrganizationDevicesOK) Error() string {
	return fmt.Sprintf("[GET /organizations/{organizationId}/devices][%d] getOrganizationDevicesOK  %+v", 200, o.Payload)
}

func (o *GetOrganizationDevicesOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetOrganizationDevicesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
