// Code generated by go-swagger; DO NOT EDIT.

package switch_ports

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetDeviceSwitchPortReader is a Reader for the GetDeviceSwitchPort structure.
type GetDeviceSwitchPortReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDeviceSwitchPortReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDeviceSwitchPortOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDeviceSwitchPortOK creates a GetDeviceSwitchPortOK with default headers values
func NewGetDeviceSwitchPortOK() *GetDeviceSwitchPortOK {
	return &GetDeviceSwitchPortOK{}
}

/*GetDeviceSwitchPortOK handles this case with default header values.

Successful operation
*/
type GetDeviceSwitchPortOK struct {
	Payload interface{}
}

func (o *GetDeviceSwitchPortOK) Error() string {
	return fmt.Sprintf("[GET /devices/{serial}/switchPorts/{number}][%d] getDeviceSwitchPortOK  %+v", 200, o.Payload)
}

func (o *GetDeviceSwitchPortOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetDeviceSwitchPortOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
