// Code generated by go-swagger; DO NOT EDIT.

package http_servers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cisco-sso/meraki-cli/models"
)

// NewCreateNetworkHTTPServerParams creates a new CreateNetworkHTTPServerParams object
// with the default values initialized.
func NewCreateNetworkHTTPServerParams() *CreateNetworkHTTPServerParams {
	var ()
	return &CreateNetworkHTTPServerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateNetworkHTTPServerParamsWithTimeout creates a new CreateNetworkHTTPServerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateNetworkHTTPServerParamsWithTimeout(timeout time.Duration) *CreateNetworkHTTPServerParams {
	var ()
	return &CreateNetworkHTTPServerParams{

		timeout: timeout,
	}
}

// NewCreateNetworkHTTPServerParamsWithContext creates a new CreateNetworkHTTPServerParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateNetworkHTTPServerParamsWithContext(ctx context.Context) *CreateNetworkHTTPServerParams {
	var ()
	return &CreateNetworkHTTPServerParams{

		Context: ctx,
	}
}

// NewCreateNetworkHTTPServerParamsWithHTTPClient creates a new CreateNetworkHTTPServerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateNetworkHTTPServerParamsWithHTTPClient(client *http.Client) *CreateNetworkHTTPServerParams {
	var ()
	return &CreateNetworkHTTPServerParams{
		HTTPClient: client,
	}
}

/*CreateNetworkHTTPServerParams contains all the parameters to send to the API endpoint
for the create network Http server operation typically these are written to a http.Request
*/
type CreateNetworkHTTPServerParams struct {

	/*CreateNetworkHTTPServer*/
	CreateNetworkHTTPServer *models.CreateNetworkHTTPServer
	/*NetworkID*/
	NetworkID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create network Http server params
func (o *CreateNetworkHTTPServerParams) WithTimeout(timeout time.Duration) *CreateNetworkHTTPServerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create network Http server params
func (o *CreateNetworkHTTPServerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create network Http server params
func (o *CreateNetworkHTTPServerParams) WithContext(ctx context.Context) *CreateNetworkHTTPServerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create network Http server params
func (o *CreateNetworkHTTPServerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create network Http server params
func (o *CreateNetworkHTTPServerParams) WithHTTPClient(client *http.Client) *CreateNetworkHTTPServerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create network Http server params
func (o *CreateNetworkHTTPServerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCreateNetworkHTTPServer adds the createNetworkHTTPServer to the create network Http server params
func (o *CreateNetworkHTTPServerParams) WithCreateNetworkHTTPServer(createNetworkHTTPServer *models.CreateNetworkHTTPServer) *CreateNetworkHTTPServerParams {
	o.SetCreateNetworkHTTPServer(createNetworkHTTPServer)
	return o
}

// SetCreateNetworkHTTPServer adds the createNetworkHttpServer to the create network Http server params
func (o *CreateNetworkHTTPServerParams) SetCreateNetworkHTTPServer(createNetworkHTTPServer *models.CreateNetworkHTTPServer) {
	o.CreateNetworkHTTPServer = createNetworkHTTPServer
}

// WithNetworkID adds the networkID to the create network Http server params
func (o *CreateNetworkHTTPServerParams) WithNetworkID(networkID string) *CreateNetworkHTTPServerParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the create network Http server params
func (o *CreateNetworkHTTPServerParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateNetworkHTTPServerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CreateNetworkHTTPServer != nil {
		if err := r.SetBodyParam(o.CreateNetworkHTTPServer); err != nil {
			return err
		}
	}

	// path param networkId
	if err := r.SetPathParam("networkId", o.NetworkID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
