// Code generated by go-swagger; DO NOT EDIT.

package http_servers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteNetworkHTTPServerReader is a Reader for the DeleteNetworkHTTPServer structure.
type DeleteNetworkHTTPServerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteNetworkHTTPServerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteNetworkHTTPServerNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteNetworkHTTPServerNoContent creates a DeleteNetworkHTTPServerNoContent with default headers values
func NewDeleteNetworkHTTPServerNoContent() *DeleteNetworkHTTPServerNoContent {
	return &DeleteNetworkHTTPServerNoContent{}
}

/*DeleteNetworkHTTPServerNoContent handles this case with default header values.

Successful operation
*/
type DeleteNetworkHTTPServerNoContent struct {
}

func (o *DeleteNetworkHTTPServerNoContent) Error() string {
	return fmt.Sprintf("[DELETE /networks/{networkId}/httpServers/{id}][%d] deleteNetworkHttpServerNoContent ", 204)
}

func (o *DeleteNetworkHTTPServerNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
