// Code generated by go-swagger; DO NOT EDIT.

package licenses

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetOrganizationLicenseParams creates a new GetOrganizationLicenseParams object
// with the default values initialized.
func NewGetOrganizationLicenseParams() *GetOrganizationLicenseParams {
	var ()
	return &GetOrganizationLicenseParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrganizationLicenseParamsWithTimeout creates a new GetOrganizationLicenseParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOrganizationLicenseParamsWithTimeout(timeout time.Duration) *GetOrganizationLicenseParams {
	var ()
	return &GetOrganizationLicenseParams{

		timeout: timeout,
	}
}

// NewGetOrganizationLicenseParamsWithContext creates a new GetOrganizationLicenseParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOrganizationLicenseParamsWithContext(ctx context.Context) *GetOrganizationLicenseParams {
	var ()
	return &GetOrganizationLicenseParams{

		Context: ctx,
	}
}

// NewGetOrganizationLicenseParamsWithHTTPClient creates a new GetOrganizationLicenseParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOrganizationLicenseParamsWithHTTPClient(client *http.Client) *GetOrganizationLicenseParams {
	var ()
	return &GetOrganizationLicenseParams{
		HTTPClient: client,
	}
}

/*GetOrganizationLicenseParams contains all the parameters to send to the API endpoint
for the get organization license operation typically these are written to a http.Request
*/
type GetOrganizationLicenseParams struct {

	/*LicenseID*/
	LicenseID string
	/*OrganizationID*/
	OrganizationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get organization license params
func (o *GetOrganizationLicenseParams) WithTimeout(timeout time.Duration) *GetOrganizationLicenseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get organization license params
func (o *GetOrganizationLicenseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get organization license params
func (o *GetOrganizationLicenseParams) WithContext(ctx context.Context) *GetOrganizationLicenseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get organization license params
func (o *GetOrganizationLicenseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get organization license params
func (o *GetOrganizationLicenseParams) WithHTTPClient(client *http.Client) *GetOrganizationLicenseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get organization license params
func (o *GetOrganizationLicenseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLicenseID adds the licenseID to the get organization license params
func (o *GetOrganizationLicenseParams) WithLicenseID(licenseID string) *GetOrganizationLicenseParams {
	o.SetLicenseID(licenseID)
	return o
}

// SetLicenseID adds the licenseId to the get organization license params
func (o *GetOrganizationLicenseParams) SetLicenseID(licenseID string) {
	o.LicenseID = licenseID
}

// WithOrganizationID adds the organizationID to the get organization license params
func (o *GetOrganizationLicenseParams) WithOrganizationID(organizationID string) *GetOrganizationLicenseParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the get organization license params
func (o *GetOrganizationLicenseParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrganizationLicenseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param licenseId
	if err := r.SetPathParam("licenseId", o.LicenseID); err != nil {
		return err
	}

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
