// Code generated by go-swagger; DO NOT EDIT.

package licenses

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cisco-sso/meraki-cli/models"
)

// NewMoveOrganizationLicensesSeatsParams creates a new MoveOrganizationLicensesSeatsParams object
// with the default values initialized.
func NewMoveOrganizationLicensesSeatsParams() *MoveOrganizationLicensesSeatsParams {
	var ()
	return &MoveOrganizationLicensesSeatsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMoveOrganizationLicensesSeatsParamsWithTimeout creates a new MoveOrganizationLicensesSeatsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMoveOrganizationLicensesSeatsParamsWithTimeout(timeout time.Duration) *MoveOrganizationLicensesSeatsParams {
	var ()
	return &MoveOrganizationLicensesSeatsParams{

		timeout: timeout,
	}
}

// NewMoveOrganizationLicensesSeatsParamsWithContext creates a new MoveOrganizationLicensesSeatsParams object
// with the default values initialized, and the ability to set a context for a request
func NewMoveOrganizationLicensesSeatsParamsWithContext(ctx context.Context) *MoveOrganizationLicensesSeatsParams {
	var ()
	return &MoveOrganizationLicensesSeatsParams{

		Context: ctx,
	}
}

// NewMoveOrganizationLicensesSeatsParamsWithHTTPClient creates a new MoveOrganizationLicensesSeatsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMoveOrganizationLicensesSeatsParamsWithHTTPClient(client *http.Client) *MoveOrganizationLicensesSeatsParams {
	var ()
	return &MoveOrganizationLicensesSeatsParams{
		HTTPClient: client,
	}
}

/*MoveOrganizationLicensesSeatsParams contains all the parameters to send to the API endpoint
for the move organization licenses seats operation typically these are written to a http.Request
*/
type MoveOrganizationLicensesSeatsParams struct {

	/*MoveOrganizationLicensesSeats*/
	MoveOrganizationLicensesSeats *models.MoveOrganizationLicensesSeats
	/*OrganizationID*/
	OrganizationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the move organization licenses seats params
func (o *MoveOrganizationLicensesSeatsParams) WithTimeout(timeout time.Duration) *MoveOrganizationLicensesSeatsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the move organization licenses seats params
func (o *MoveOrganizationLicensesSeatsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the move organization licenses seats params
func (o *MoveOrganizationLicensesSeatsParams) WithContext(ctx context.Context) *MoveOrganizationLicensesSeatsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the move organization licenses seats params
func (o *MoveOrganizationLicensesSeatsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the move organization licenses seats params
func (o *MoveOrganizationLicensesSeatsParams) WithHTTPClient(client *http.Client) *MoveOrganizationLicensesSeatsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the move organization licenses seats params
func (o *MoveOrganizationLicensesSeatsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMoveOrganizationLicensesSeats adds the moveOrganizationLicensesSeats to the move organization licenses seats params
func (o *MoveOrganizationLicensesSeatsParams) WithMoveOrganizationLicensesSeats(moveOrganizationLicensesSeats *models.MoveOrganizationLicensesSeats) *MoveOrganizationLicensesSeatsParams {
	o.SetMoveOrganizationLicensesSeats(moveOrganizationLicensesSeats)
	return o
}

// SetMoveOrganizationLicensesSeats adds the moveOrganizationLicensesSeats to the move organization licenses seats params
func (o *MoveOrganizationLicensesSeatsParams) SetMoveOrganizationLicensesSeats(moveOrganizationLicensesSeats *models.MoveOrganizationLicensesSeats) {
	o.MoveOrganizationLicensesSeats = moveOrganizationLicensesSeats
}

// WithOrganizationID adds the organizationID to the move organization licenses seats params
func (o *MoveOrganizationLicensesSeatsParams) WithOrganizationID(organizationID string) *MoveOrganizationLicensesSeatsParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the move organization licenses seats params
func (o *MoveOrganizationLicensesSeatsParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WriteToRequest writes these params to a swagger request
func (o *MoveOrganizationLicensesSeatsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.MoveOrganizationLicensesSeats != nil {
		if err := r.SetBodyParam(o.MoveOrganizationLicensesSeats); err != nil {
			return err
		}
	}

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
