// Code generated by go-swagger; DO NOT EDIT.

package licenses

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// MoveOrganizationLicensesReader is a Reader for the MoveOrganizationLicenses structure.
type MoveOrganizationLicensesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MoveOrganizationLicensesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMoveOrganizationLicensesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewMoveOrganizationLicensesOK creates a MoveOrganizationLicensesOK with default headers values
func NewMoveOrganizationLicensesOK() *MoveOrganizationLicensesOK {
	return &MoveOrganizationLicensesOK{}
}

/*MoveOrganizationLicensesOK handles this case with default header values.

Successful operation
*/
type MoveOrganizationLicensesOK struct {
	Payload interface{}
}

func (o *MoveOrganizationLicensesOK) Error() string {
	return fmt.Sprintf("[POST /organizations/{organizationId}/licenses/move][%d] moveOrganizationLicensesOK  %+v", 200, o.Payload)
}

func (o *MoveOrganizationLicensesOK) GetPayload() interface{} {
	return o.Payload
}

func (o *MoveOrganizationLicensesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
