// Code generated by go-swagger; DO NOT EDIT.

package management_interface_settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetNetworkDeviceManagementInterfaceSettingsReader is a Reader for the GetNetworkDeviceManagementInterfaceSettings structure.
type GetNetworkDeviceManagementInterfaceSettingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNetworkDeviceManagementInterfaceSettingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNetworkDeviceManagementInterfaceSettingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetNetworkDeviceManagementInterfaceSettingsOK creates a GetNetworkDeviceManagementInterfaceSettingsOK with default headers values
func NewGetNetworkDeviceManagementInterfaceSettingsOK() *GetNetworkDeviceManagementInterfaceSettingsOK {
	return &GetNetworkDeviceManagementInterfaceSettingsOK{}
}

/*GetNetworkDeviceManagementInterfaceSettingsOK handles this case with default header values.

Successful operation
*/
type GetNetworkDeviceManagementInterfaceSettingsOK struct {
	Payload interface{}
}

func (o *GetNetworkDeviceManagementInterfaceSettingsOK) Error() string {
	return fmt.Sprintf("[GET /networks/{networkId}/devices/{serial}/managementInterfaceSettings][%d] getNetworkDeviceManagementInterfaceSettingsOK  %+v", 200, o.Payload)
}

func (o *GetNetworkDeviceManagementInterfaceSettingsOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetNetworkDeviceManagementInterfaceSettingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
