// Code generated by go-swagger; DO NOT EDIT.

package security_events

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetOrganizationSecurityEventsReader is a Reader for the GetOrganizationSecurityEvents structure.
type GetOrganizationSecurityEventsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrganizationSecurityEventsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOrganizationSecurityEventsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetOrganizationSecurityEventsOK creates a GetOrganizationSecurityEventsOK with default headers values
func NewGetOrganizationSecurityEventsOK() *GetOrganizationSecurityEventsOK {
	return &GetOrganizationSecurityEventsOK{}
}

/*GetOrganizationSecurityEventsOK handles this case with default header values.

Successful operation
*/
type GetOrganizationSecurityEventsOK struct {
	Payload interface{}
}

func (o *GetOrganizationSecurityEventsOK) Error() string {
	return fmt.Sprintf("[GET /organizations/{organizationId}/securityEvents][%d] getOrganizationSecurityEventsOK  %+v", 200, o.Payload)
}

func (o *GetOrganizationSecurityEventsOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetOrganizationSecurityEventsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
