// Code generated by go-swagger; DO NOT EDIT.

package m_x_v_l_a_n_ports

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetNetworkAppliancePortsReader is a Reader for the GetNetworkAppliancePorts structure.
type GetNetworkAppliancePortsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNetworkAppliancePortsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNetworkAppliancePortsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetNetworkAppliancePortsOK creates a GetNetworkAppliancePortsOK with default headers values
func NewGetNetworkAppliancePortsOK() *GetNetworkAppliancePortsOK {
	return &GetNetworkAppliancePortsOK{}
}

/*GetNetworkAppliancePortsOK handles this case with default header values.

Successful operation
*/
type GetNetworkAppliancePortsOK struct {
	Payload interface{}
}

func (o *GetNetworkAppliancePortsOK) Error() string {
	return fmt.Sprintf("[GET /networks/{networkId}/appliancePorts][%d] getNetworkAppliancePortsOK  %+v", 200, o.Payload)
}

func (o *GetNetworkAppliancePortsOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetNetworkAppliancePortsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
