// Code generated by go-swagger; DO NOT EDIT.

package m_x_v_l_a_n_ports

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetNetworkAppliancePortReader is a Reader for the GetNetworkAppliancePort structure.
type GetNetworkAppliancePortReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNetworkAppliancePortReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNetworkAppliancePortOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetNetworkAppliancePortOK creates a GetNetworkAppliancePortOK with default headers values
func NewGetNetworkAppliancePortOK() *GetNetworkAppliancePortOK {
	return &GetNetworkAppliancePortOK{}
}

/*GetNetworkAppliancePortOK handles this case with default header values.

Successful operation
*/
type GetNetworkAppliancePortOK struct {
	Payload interface{}
}

func (o *GetNetworkAppliancePortOK) Error() string {
	return fmt.Sprintf("[GET /networks/{networkId}/appliancePorts/{appliancePortId}][%d] getNetworkAppliancePortOK  %+v", 200, o.Payload)
}

func (o *GetNetworkAppliancePortOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetNetworkAppliancePortOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
