// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetNetworkAccessPoliciesReader is a Reader for the GetNetworkAccessPolicies structure.
type GetNetworkAccessPoliciesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNetworkAccessPoliciesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNetworkAccessPoliciesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetNetworkAccessPoliciesOK creates a GetNetworkAccessPoliciesOK with default headers values
func NewGetNetworkAccessPoliciesOK() *GetNetworkAccessPoliciesOK {
	return &GetNetworkAccessPoliciesOK{}
}

/*GetNetworkAccessPoliciesOK handles this case with default header values.

Successful operation
*/
type GetNetworkAccessPoliciesOK struct {
	Payload interface{}
}

func (o *GetNetworkAccessPoliciesOK) Error() string {
	return fmt.Sprintf("[GET /networks/{networkId}/accessPolicies][%d] getNetworkAccessPoliciesOK  %+v", 200, o.Payload)
}

func (o *GetNetworkAccessPoliciesOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetNetworkAccessPoliciesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
