// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetOrganizationNetworksParams creates a new GetOrganizationNetworksParams object
// with the default values initialized.
func NewGetOrganizationNetworksParams() *GetOrganizationNetworksParams {
	var ()
	return &GetOrganizationNetworksParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrganizationNetworksParamsWithTimeout creates a new GetOrganizationNetworksParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetOrganizationNetworksParamsWithTimeout(timeout time.Duration) *GetOrganizationNetworksParams {
	var ()
	return &GetOrganizationNetworksParams{

		timeout: timeout,
	}
}

// NewGetOrganizationNetworksParamsWithContext creates a new GetOrganizationNetworksParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetOrganizationNetworksParamsWithContext(ctx context.Context) *GetOrganizationNetworksParams {
	var ()
	return &GetOrganizationNetworksParams{

		Context: ctx,
	}
}

// NewGetOrganizationNetworksParamsWithHTTPClient creates a new GetOrganizationNetworksParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetOrganizationNetworksParamsWithHTTPClient(client *http.Client) *GetOrganizationNetworksParams {
	var ()
	return &GetOrganizationNetworksParams{
		HTTPClient: client,
	}
}

/*GetOrganizationNetworksParams contains all the parameters to send to the API endpoint
for the get organization networks operation typically these are written to a http.Request
*/
type GetOrganizationNetworksParams struct {

	/*ConfigTemplateID
	  An optional parameter that is the ID of a config template. Will return all networks bound to that template.

	*/
	ConfigTemplateID *string
	/*OrganizationID*/
	OrganizationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get organization networks params
func (o *GetOrganizationNetworksParams) WithTimeout(timeout time.Duration) *GetOrganizationNetworksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get organization networks params
func (o *GetOrganizationNetworksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get organization networks params
func (o *GetOrganizationNetworksParams) WithContext(ctx context.Context) *GetOrganizationNetworksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get organization networks params
func (o *GetOrganizationNetworksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get organization networks params
func (o *GetOrganizationNetworksParams) WithHTTPClient(client *http.Client) *GetOrganizationNetworksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get organization networks params
func (o *GetOrganizationNetworksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConfigTemplateID adds the configTemplateID to the get organization networks params
func (o *GetOrganizationNetworksParams) WithConfigTemplateID(configTemplateID *string) *GetOrganizationNetworksParams {
	o.SetConfigTemplateID(configTemplateID)
	return o
}

// SetConfigTemplateID adds the configTemplateId to the get organization networks params
func (o *GetOrganizationNetworksParams) SetConfigTemplateID(configTemplateID *string) {
	o.ConfigTemplateID = configTemplateID
}

// WithOrganizationID adds the organizationID to the get organization networks params
func (o *GetOrganizationNetworksParams) WithOrganizationID(organizationID string) *GetOrganizationNetworksParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the get organization networks params
func (o *GetOrganizationNetworksParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrganizationNetworksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ConfigTemplateID != nil {

		// query param configTemplateId
		var qrConfigTemplateID string
		if o.ConfigTemplateID != nil {
			qrConfigTemplateID = *o.ConfigTemplateID
		}
		qConfigTemplateID := qrConfigTemplateID
		if qConfigTemplateID != "" {
			if err := r.SetQueryParam("configTemplateId", qConfigTemplateID); err != nil {
				return err
			}
		}

	}

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
