// Code generated by go-swagger; DO NOT EDIT.

package floorplans

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateNetworkFloorPlanReader is a Reader for the CreateNetworkFloorPlan structure.
type CreateNetworkFloorPlanReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateNetworkFloorPlanReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateNetworkFloorPlanCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateNetworkFloorPlanCreated creates a CreateNetworkFloorPlanCreated with default headers values
func NewCreateNetworkFloorPlanCreated() *CreateNetworkFloorPlanCreated {
	return &CreateNetworkFloorPlanCreated{}
}

/*CreateNetworkFloorPlanCreated handles this case with default header values.

Successful operation
*/
type CreateNetworkFloorPlanCreated struct {
	Payload interface{}
}

func (o *CreateNetworkFloorPlanCreated) Error() string {
	return fmt.Sprintf("[POST /networks/{networkId}/floorPlans][%d] createNetworkFloorPlanCreated  %+v", 201, o.Payload)
}

func (o *CreateNetworkFloorPlanCreated) GetPayload() interface{} {
	return o.Payload
}

func (o *CreateNetworkFloorPlanCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
