// Code generated by go-swagger; DO NOT EDIT.

package wireless_health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetNetworkClientLatencyStatsReader is a Reader for the GetNetworkClientLatencyStats structure.
type GetNetworkClientLatencyStatsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNetworkClientLatencyStatsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNetworkClientLatencyStatsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetNetworkClientLatencyStatsOK creates a GetNetworkClientLatencyStatsOK with default headers values
func NewGetNetworkClientLatencyStatsOK() *GetNetworkClientLatencyStatsOK {
	return &GetNetworkClientLatencyStatsOK{}
}

/*GetNetworkClientLatencyStatsOK handles this case with default header values.

Successful operation
*/
type GetNetworkClientLatencyStatsOK struct {
	Payload interface{}
}

func (o *GetNetworkClientLatencyStatsOK) Error() string {
	return fmt.Sprintf("[GET /networks/{networkId}/clients/{clientId}/latencyStats][%d] getNetworkClientLatencyStatsOK  %+v", 200, o.Payload)
}

func (o *GetNetworkClientLatencyStatsOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetNetworkClientLatencyStatsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
