// Code generated by go-swagger; DO NOT EDIT.

package cameras

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateDeviceCameraQualityAndRetentionSettingsReader is a Reader for the UpdateDeviceCameraQualityAndRetentionSettings structure.
type UpdateDeviceCameraQualityAndRetentionSettingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateDeviceCameraQualityAndRetentionSettingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateDeviceCameraQualityAndRetentionSettingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateDeviceCameraQualityAndRetentionSettingsOK creates a UpdateDeviceCameraQualityAndRetentionSettingsOK with default headers values
func NewUpdateDeviceCameraQualityAndRetentionSettingsOK() *UpdateDeviceCameraQualityAndRetentionSettingsOK {
	return &UpdateDeviceCameraQualityAndRetentionSettingsOK{}
}

/*UpdateDeviceCameraQualityAndRetentionSettingsOK handles this case with default header values.

Successful operation
*/
type UpdateDeviceCameraQualityAndRetentionSettingsOK struct {
	Payload interface{}
}

func (o *UpdateDeviceCameraQualityAndRetentionSettingsOK) Error() string {
	return fmt.Sprintf("[PUT /devices/{serial}/camera/qualityAndRetentionSettings][%d] updateDeviceCameraQualityAndRetentionSettingsOK  %+v", 200, o.Payload)
}

func (o *UpdateDeviceCameraQualityAndRetentionSettingsOK) GetPayload() interface{} {
	return o.Payload
}

func (o *UpdateDeviceCameraQualityAndRetentionSettingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
