// Code generated by go-swagger; DO NOT EDIT.

package m_g_l_a_n_settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new m g l a n settings API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for m g l a n settings API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetDeviceCellularGatewaySettings(params *GetDeviceCellularGatewaySettingsParams, authInfo runtime.ClientAuthInfoWriter) (*GetDeviceCellularGatewaySettingsOK, error)

	UpdateDeviceCellularGatewaySettings(params *UpdateDeviceCellularGatewaySettingsParams, authInfo runtime.ClientAuthInfoWriter) (*UpdateDeviceCellularGatewaySettingsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetDeviceCellularGatewaySettings gets device cellular gateway settings

  Show the LAN Settings of a MG
*/
func (a *Client) GetDeviceCellularGatewaySettings(params *GetDeviceCellularGatewaySettingsParams, authInfo runtime.ClientAuthInfoWriter) (*GetDeviceCellularGatewaySettingsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetDeviceCellularGatewaySettingsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getDeviceCellularGatewaySettings",
		Method:             "GET",
		PathPattern:        "/devices/{serial}/cellularGateway/settings",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetDeviceCellularGatewaySettingsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetDeviceCellularGatewaySettingsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getDeviceCellularGatewaySettings: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  UpdateDeviceCellularGatewaySettings updates device cellular gateway settings

  Update the LAN Settings for a single MG.
*/
func (a *Client) UpdateDeviceCellularGatewaySettings(params *UpdateDeviceCellularGatewaySettingsParams, authInfo runtime.ClientAuthInfoWriter) (*UpdateDeviceCellularGatewaySettingsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateDeviceCellularGatewaySettingsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "updateDeviceCellularGatewaySettings",
		Method:             "PUT",
		PathPattern:        "/devices/{serial}/cellularGateway/settings",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &UpdateDeviceCellularGatewaySettingsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateDeviceCellularGatewaySettingsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for updateDeviceCellularGatewaySettings: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
