// Code generated by go-swagger; DO NOT EDIT.

package dashboard_branding_policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteOrganizationBrandingPolicyParams creates a new DeleteOrganizationBrandingPolicyParams object
// with the default values initialized.
func NewDeleteOrganizationBrandingPolicyParams() *DeleteOrganizationBrandingPolicyParams {
	var ()
	return &DeleteOrganizationBrandingPolicyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteOrganizationBrandingPolicyParamsWithTimeout creates a new DeleteOrganizationBrandingPolicyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteOrganizationBrandingPolicyParamsWithTimeout(timeout time.Duration) *DeleteOrganizationBrandingPolicyParams {
	var ()
	return &DeleteOrganizationBrandingPolicyParams{

		timeout: timeout,
	}
}

// NewDeleteOrganizationBrandingPolicyParamsWithContext creates a new DeleteOrganizationBrandingPolicyParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteOrganizationBrandingPolicyParamsWithContext(ctx context.Context) *DeleteOrganizationBrandingPolicyParams {
	var ()
	return &DeleteOrganizationBrandingPolicyParams{

		Context: ctx,
	}
}

// NewDeleteOrganizationBrandingPolicyParamsWithHTTPClient creates a new DeleteOrganizationBrandingPolicyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteOrganizationBrandingPolicyParamsWithHTTPClient(client *http.Client) *DeleteOrganizationBrandingPolicyParams {
	var ()
	return &DeleteOrganizationBrandingPolicyParams{
		HTTPClient: client,
	}
}

/*DeleteOrganizationBrandingPolicyParams contains all the parameters to send to the API endpoint
for the delete organization branding policy operation typically these are written to a http.Request
*/
type DeleteOrganizationBrandingPolicyParams struct {

	/*BrandingPolicyID*/
	BrandingPolicyID string
	/*OrganizationID*/
	OrganizationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete organization branding policy params
func (o *DeleteOrganizationBrandingPolicyParams) WithTimeout(timeout time.Duration) *DeleteOrganizationBrandingPolicyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete organization branding policy params
func (o *DeleteOrganizationBrandingPolicyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete organization branding policy params
func (o *DeleteOrganizationBrandingPolicyParams) WithContext(ctx context.Context) *DeleteOrganizationBrandingPolicyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete organization branding policy params
func (o *DeleteOrganizationBrandingPolicyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete organization branding policy params
func (o *DeleteOrganizationBrandingPolicyParams) WithHTTPClient(client *http.Client) *DeleteOrganizationBrandingPolicyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete organization branding policy params
func (o *DeleteOrganizationBrandingPolicyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBrandingPolicyID adds the brandingPolicyID to the delete organization branding policy params
func (o *DeleteOrganizationBrandingPolicyParams) WithBrandingPolicyID(brandingPolicyID string) *DeleteOrganizationBrandingPolicyParams {
	o.SetBrandingPolicyID(brandingPolicyID)
	return o
}

// SetBrandingPolicyID adds the brandingPolicyId to the delete organization branding policy params
func (o *DeleteOrganizationBrandingPolicyParams) SetBrandingPolicyID(brandingPolicyID string) {
	o.BrandingPolicyID = brandingPolicyID
}

// WithOrganizationID adds the organizationID to the delete organization branding policy params
func (o *DeleteOrganizationBrandingPolicyParams) WithOrganizationID(organizationID string) *DeleteOrganizationBrandingPolicyParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the delete organization branding policy params
func (o *DeleteOrganizationBrandingPolicyParams) SetOrganizationID(organizationID string) {
	o.OrganizationID = organizationID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteOrganizationBrandingPolicyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param brandingPolicyId
	if err := r.SetPathParam("brandingPolicyId", o.BrandingPolicyID); err != nil {
		return err
	}

	// path param organizationId
	if err := r.SetPathParam("organizationId", o.OrganizationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
