// Code generated by go-swagger; DO NOT EDIT.

package dashboard_branding_policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateOrganizationBrandingPolicyReader is a Reader for the UpdateOrganizationBrandingPolicy structure.
type UpdateOrganizationBrandingPolicyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateOrganizationBrandingPolicyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateOrganizationBrandingPolicyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateOrganizationBrandingPolicyOK creates a UpdateOrganizationBrandingPolicyOK with default headers values
func NewUpdateOrganizationBrandingPolicyOK() *UpdateOrganizationBrandingPolicyOK {
	return &UpdateOrganizationBrandingPolicyOK{}
}

/*UpdateOrganizationBrandingPolicyOK handles this case with default header values.

Successful operation
*/
type UpdateOrganizationBrandingPolicyOK struct {
	Payload interface{}
}

func (o *UpdateOrganizationBrandingPolicyOK) Error() string {
	return fmt.Sprintf("[PUT /organizations/{organizationId}/brandingPolicies/{brandingPolicyId}][%d] updateOrganizationBrandingPolicyOK  %+v", 200, o.Payload)
}

func (o *UpdateOrganizationBrandingPolicyOK) GetPayload() interface{} {
	return o.Payload
}

func (o *UpdateOrganizationBrandingPolicyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
