// Code generated by go-swagger; DO NOT EDIT.

package switch_settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetNetworkSwitchSettingsQosRuleReader is a Reader for the GetNetworkSwitchSettingsQosRule structure.
type GetNetworkSwitchSettingsQosRuleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNetworkSwitchSettingsQosRuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNetworkSwitchSettingsQosRuleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetNetworkSwitchSettingsQosRuleOK creates a GetNetworkSwitchSettingsQosRuleOK with default headers values
func NewGetNetworkSwitchSettingsQosRuleOK() *GetNetworkSwitchSettingsQosRuleOK {
	return &GetNetworkSwitchSettingsQosRuleOK{}
}

/*GetNetworkSwitchSettingsQosRuleOK handles this case with default header values.

Successful operation
*/
type GetNetworkSwitchSettingsQosRuleOK struct {
	Payload interface{}
}

func (o *GetNetworkSwitchSettingsQosRuleOK) Error() string {
	return fmt.Sprintf("[GET /networks/{networkId}/switch/settings/qosRules/{qosRuleId}][%d] getNetworkSwitchSettingsQosRuleOK  %+v", 200, o.Payload)
}

func (o *GetNetworkSwitchSettingsQosRuleOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetNetworkSwitchSettingsQosRuleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
