// Code generated by go-swagger; DO NOT EDIT.

package switch_settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetNetworkSwitchSettingsMulticastReader is a Reader for the GetNetworkSwitchSettingsMulticast structure.
type GetNetworkSwitchSettingsMulticastReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNetworkSwitchSettingsMulticastReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNetworkSwitchSettingsMulticastOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetNetworkSwitchSettingsMulticastOK creates a GetNetworkSwitchSettingsMulticastOK with default headers values
func NewGetNetworkSwitchSettingsMulticastOK() *GetNetworkSwitchSettingsMulticastOK {
	return &GetNetworkSwitchSettingsMulticastOK{}
}

/*GetNetworkSwitchSettingsMulticastOK handles this case with default header values.

Successful operation
*/
type GetNetworkSwitchSettingsMulticastOK struct {
	Payload interface{}
}

func (o *GetNetworkSwitchSettingsMulticastOK) Error() string {
	return fmt.Sprintf("[GET /networks/{networkId}/switch/settings/multicast][%d] getNetworkSwitchSettingsMulticastOK  %+v", 200, o.Payload)
}

func (o *GetNetworkSwitchSettingsMulticastOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetNetworkSwitchSettingsMulticastOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
