// Code generated by go-swagger; DO NOT EDIT.

package switch_settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetNetworkSwitchSettingsMtuReader is a Reader for the GetNetworkSwitchSettingsMtu structure.
type GetNetworkSwitchSettingsMtuReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNetworkSwitchSettingsMtuReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNetworkSwitchSettingsMtuOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetNetworkSwitchSettingsMtuOK creates a GetNetworkSwitchSettingsMtuOK with default headers values
func NewGetNetworkSwitchSettingsMtuOK() *GetNetworkSwitchSettingsMtuOK {
	return &GetNetworkSwitchSettingsMtuOK{}
}

/*GetNetworkSwitchSettingsMtuOK handles this case with default header values.

Successful operation
*/
type GetNetworkSwitchSettingsMtuOK struct {
	Payload interface{}
}

func (o *GetNetworkSwitchSettingsMtuOK) Error() string {
	return fmt.Sprintf("[GET /networks/{networkId}/switch/settings/mtu][%d] getNetworkSwitchSettingsMtuOK  %+v", 200, o.Payload)
}

func (o *GetNetworkSwitchSettingsMtuOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetNetworkSwitchSettingsMtuOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
