// Code generated by go-swagger; DO NOT EDIT.

package switch_settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateNetworkSwitchSettingsDscpToCosMappingsReader is a Reader for the UpdateNetworkSwitchSettingsDscpToCosMappings structure.
type UpdateNetworkSwitchSettingsDscpToCosMappingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateNetworkSwitchSettingsDscpToCosMappingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateNetworkSwitchSettingsDscpToCosMappingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateNetworkSwitchSettingsDscpToCosMappingsOK creates a UpdateNetworkSwitchSettingsDscpToCosMappingsOK with default headers values
func NewUpdateNetworkSwitchSettingsDscpToCosMappingsOK() *UpdateNetworkSwitchSettingsDscpToCosMappingsOK {
	return &UpdateNetworkSwitchSettingsDscpToCosMappingsOK{}
}

/*UpdateNetworkSwitchSettingsDscpToCosMappingsOK handles this case with default header values.

Successful operation
*/
type UpdateNetworkSwitchSettingsDscpToCosMappingsOK struct {
	Payload interface{}
}

func (o *UpdateNetworkSwitchSettingsDscpToCosMappingsOK) Error() string {
	return fmt.Sprintf("[PUT /networks/{networkId}/switch/settings/dscpToCosMappings][%d] updateNetworkSwitchSettingsDscpToCosMappingsOK  %+v", 200, o.Payload)
}

func (o *UpdateNetworkSwitchSettingsDscpToCosMappingsOK) GetPayload() interface{} {
	return o.Payload
}

func (o *UpdateNetworkSwitchSettingsDscpToCosMappingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
