// Code generated by go-swagger; DO NOT EDIT.

package switch_settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateNetworkSwitchSettingsQosRulesOrderReader is a Reader for the UpdateNetworkSwitchSettingsQosRulesOrder structure.
type UpdateNetworkSwitchSettingsQosRulesOrderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateNetworkSwitchSettingsQosRulesOrderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateNetworkSwitchSettingsQosRulesOrderOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateNetworkSwitchSettingsQosRulesOrderOK creates a UpdateNetworkSwitchSettingsQosRulesOrderOK with default headers values
func NewUpdateNetworkSwitchSettingsQosRulesOrderOK() *UpdateNetworkSwitchSettingsQosRulesOrderOK {
	return &UpdateNetworkSwitchSettingsQosRulesOrderOK{}
}

/*UpdateNetworkSwitchSettingsQosRulesOrderOK handles this case with default header values.

Successful operation
*/
type UpdateNetworkSwitchSettingsQosRulesOrderOK struct {
	Payload interface{}
}

func (o *UpdateNetworkSwitchSettingsQosRulesOrderOK) Error() string {
	return fmt.Sprintf("[PUT /networks/{networkId}/switch/settings/qosRules/order][%d] updateNetworkSwitchSettingsQosRulesOrderOK  %+v", 200, o.Payload)
}

func (o *UpdateNetworkSwitchSettingsQosRulesOrderOK) GetPayload() interface{} {
	return o.Payload
}

func (o *UpdateNetworkSwitchSettingsQosRulesOrderOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
