// Code generated by go-swagger; DO NOT EDIT.

package radio_settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetNetworkWirelessRfProfileReader is a Reader for the GetNetworkWirelessRfProfile structure.
type GetNetworkWirelessRfProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNetworkWirelessRfProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNetworkWirelessRfProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetNetworkWirelessRfProfileOK creates a GetNetworkWirelessRfProfileOK with default headers values
func NewGetNetworkWirelessRfProfileOK() *GetNetworkWirelessRfProfileOK {
	return &GetNetworkWirelessRfProfileOK{}
}

/*GetNetworkWirelessRfProfileOK handles this case with default header values.

Successful operation
*/
type GetNetworkWirelessRfProfileOK struct {
	Payload interface{}
}

func (o *GetNetworkWirelessRfProfileOK) Error() string {
	return fmt.Sprintf("[GET /networks/{networkId}/wireless/rfProfiles/{rfProfileId}][%d] getNetworkWirelessRfProfileOK  %+v", 200, o.Payload)
}

func (o *GetNetworkWirelessRfProfileOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetNetworkWirelessRfProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
