// Code generated by go-swagger; DO NOT EDIT.

package link_aggregations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteNetworkSwitchLinkAggregationReader is a Reader for the DeleteNetworkSwitchLinkAggregation structure.
type DeleteNetworkSwitchLinkAggregationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteNetworkSwitchLinkAggregationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteNetworkSwitchLinkAggregationNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteNetworkSwitchLinkAggregationNoContent creates a DeleteNetworkSwitchLinkAggregationNoContent with default headers values
func NewDeleteNetworkSwitchLinkAggregationNoContent() *DeleteNetworkSwitchLinkAggregationNoContent {
	return &DeleteNetworkSwitchLinkAggregationNoContent{}
}

/*DeleteNetworkSwitchLinkAggregationNoContent handles this case with default header values.

Successful operation
*/
type DeleteNetworkSwitchLinkAggregationNoContent struct {
}

func (o *DeleteNetworkSwitchLinkAggregationNoContent) Error() string {
	return fmt.Sprintf("[DELETE /networks/{networkId}/switch/linkAggregations/{linkAggregationId}][%d] deleteNetworkSwitchLinkAggregationNoContent ", 204)
}

func (o *DeleteNetworkSwitchLinkAggregationNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
