// Code generated by go-swagger; DO NOT EDIT.

package link_aggregations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateNetworkSwitchLinkAggregationReader is a Reader for the UpdateNetworkSwitchLinkAggregation structure.
type UpdateNetworkSwitchLinkAggregationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateNetworkSwitchLinkAggregationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateNetworkSwitchLinkAggregationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateNetworkSwitchLinkAggregationOK creates a UpdateNetworkSwitchLinkAggregationOK with default headers values
func NewUpdateNetworkSwitchLinkAggregationOK() *UpdateNetworkSwitchLinkAggregationOK {
	return &UpdateNetworkSwitchLinkAggregationOK{}
}

/*UpdateNetworkSwitchLinkAggregationOK handles this case with default header values.

Successful operation
*/
type UpdateNetworkSwitchLinkAggregationOK struct {
	Payload interface{}
}

func (o *UpdateNetworkSwitchLinkAggregationOK) Error() string {
	return fmt.Sprintf("[PUT /networks/{networkId}/switch/linkAggregations/{linkAggregationId}][%d] updateNetworkSwitchLinkAggregationOK  %+v", 200, o.Payload)
}

func (o *UpdateNetworkSwitchLinkAggregationOK) GetPayload() interface{} {
	return o.Payload
}

func (o *UpdateNetworkSwitchLinkAggregationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
