// Code generated by go-swagger; DO NOT EDIT.

package s_m

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteNetworkSmAppPolarisParams creates a new DeleteNetworkSmAppPolarisParams object
// with the default values initialized.
func NewDeleteNetworkSmAppPolarisParams() *DeleteNetworkSmAppPolarisParams {
	var ()
	return &DeleteNetworkSmAppPolarisParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteNetworkSmAppPolarisParamsWithTimeout creates a new DeleteNetworkSmAppPolarisParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteNetworkSmAppPolarisParamsWithTimeout(timeout time.Duration) *DeleteNetworkSmAppPolarisParams {
	var ()
	return &DeleteNetworkSmAppPolarisParams{

		timeout: timeout,
	}
}

// NewDeleteNetworkSmAppPolarisParamsWithContext creates a new DeleteNetworkSmAppPolarisParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteNetworkSmAppPolarisParamsWithContext(ctx context.Context) *DeleteNetworkSmAppPolarisParams {
	var ()
	return &DeleteNetworkSmAppPolarisParams{

		Context: ctx,
	}
}

// NewDeleteNetworkSmAppPolarisParamsWithHTTPClient creates a new DeleteNetworkSmAppPolarisParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteNetworkSmAppPolarisParamsWithHTTPClient(client *http.Client) *DeleteNetworkSmAppPolarisParams {
	var ()
	return &DeleteNetworkSmAppPolarisParams{
		HTTPClient: client,
	}
}

/*DeleteNetworkSmAppPolarisParams contains all the parameters to send to the API endpoint
for the delete network sm app polaris operation typically these are written to a http.Request
*/
type DeleteNetworkSmAppPolarisParams struct {

	/*AppID*/
	AppID string
	/*NetworkID*/
	NetworkID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete network sm app polaris params
func (o *DeleteNetworkSmAppPolarisParams) WithTimeout(timeout time.Duration) *DeleteNetworkSmAppPolarisParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete network sm app polaris params
func (o *DeleteNetworkSmAppPolarisParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete network sm app polaris params
func (o *DeleteNetworkSmAppPolarisParams) WithContext(ctx context.Context) *DeleteNetworkSmAppPolarisParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete network sm app polaris params
func (o *DeleteNetworkSmAppPolarisParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete network sm app polaris params
func (o *DeleteNetworkSmAppPolarisParams) WithHTTPClient(client *http.Client) *DeleteNetworkSmAppPolarisParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete network sm app polaris params
func (o *DeleteNetworkSmAppPolarisParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the delete network sm app polaris params
func (o *DeleteNetworkSmAppPolarisParams) WithAppID(appID string) *DeleteNetworkSmAppPolarisParams {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the delete network sm app polaris params
func (o *DeleteNetworkSmAppPolarisParams) SetAppID(appID string) {
	o.AppID = appID
}

// WithNetworkID adds the networkID to the delete network sm app polaris params
func (o *DeleteNetworkSmAppPolarisParams) WithNetworkID(networkID string) *DeleteNetworkSmAppPolarisParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the delete network sm app polaris params
func (o *DeleteNetworkSmAppPolarisParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteNetworkSmAppPolarisParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appId
	if err := r.SetPathParam("appId", o.AppID); err != nil {
		return err
	}

	// path param networkId
	if err := r.SetPathParam("networkId", o.NetworkID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
