// Code generated by go-swagger; DO NOT EDIT.

package s_m

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetNetworkSmConnectivityReader is a Reader for the GetNetworkSmConnectivity structure.
type GetNetworkSmConnectivityReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNetworkSmConnectivityReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNetworkSmConnectivityOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetNetworkSmConnectivityOK creates a GetNetworkSmConnectivityOK with default headers values
func NewGetNetworkSmConnectivityOK() *GetNetworkSmConnectivityOK {
	return &GetNetworkSmConnectivityOK{}
}

/*GetNetworkSmConnectivityOK handles this case with default header values.

Successful operation
*/
type GetNetworkSmConnectivityOK struct {
	Payload interface{}
}

func (o *GetNetworkSmConnectivityOK) Error() string {
	return fmt.Sprintf("[GET /networks/{network_id}/sm/{id}/connectivity][%d] getNetworkSmConnectivityOK  %+v", 200, o.Payload)
}

func (o *GetNetworkSmConnectivityOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetNetworkSmConnectivityOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
