// Code generated by go-swagger; DO NOT EDIT.

package s_m

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetNetworkSmUserSoftwaresReader is a Reader for the GetNetworkSmUserSoftwares structure.
type GetNetworkSmUserSoftwaresReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNetworkSmUserSoftwaresReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNetworkSmUserSoftwaresOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetNetworkSmUserSoftwaresOK creates a GetNetworkSmUserSoftwaresOK with default headers values
func NewGetNetworkSmUserSoftwaresOK() *GetNetworkSmUserSoftwaresOK {
	return &GetNetworkSmUserSoftwaresOK{}
}

/*GetNetworkSmUserSoftwaresOK handles this case with default header values.

Successful operation
*/
type GetNetworkSmUserSoftwaresOK struct {
	Payload interface{}
}

func (o *GetNetworkSmUserSoftwaresOK) Error() string {
	return fmt.Sprintf("[GET /networks/{networkId}/sm/user/{userId}/softwares][%d] getNetworkSmUserSoftwaresOK  %+v", 200, o.Payload)
}

func (o *GetNetworkSmUserSoftwaresOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetNetworkSmUserSoftwaresOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
