// Code generated by go-swagger; DO NOT EDIT.

package s_m

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cisco-sso/meraki-cli/models"
)

// NewUpdateNetworkSmDeviceFieldsParams creates a new UpdateNetworkSmDeviceFieldsParams object
// with the default values initialized.
func NewUpdateNetworkSmDeviceFieldsParams() *UpdateNetworkSmDeviceFieldsParams {
	var ()
	return &UpdateNetworkSmDeviceFieldsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateNetworkSmDeviceFieldsParamsWithTimeout creates a new UpdateNetworkSmDeviceFieldsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateNetworkSmDeviceFieldsParamsWithTimeout(timeout time.Duration) *UpdateNetworkSmDeviceFieldsParams {
	var ()
	return &UpdateNetworkSmDeviceFieldsParams{

		timeout: timeout,
	}
}

// NewUpdateNetworkSmDeviceFieldsParamsWithContext creates a new UpdateNetworkSmDeviceFieldsParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateNetworkSmDeviceFieldsParamsWithContext(ctx context.Context) *UpdateNetworkSmDeviceFieldsParams {
	var ()
	return &UpdateNetworkSmDeviceFieldsParams{

		Context: ctx,
	}
}

// NewUpdateNetworkSmDeviceFieldsParamsWithHTTPClient creates a new UpdateNetworkSmDeviceFieldsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateNetworkSmDeviceFieldsParamsWithHTTPClient(client *http.Client) *UpdateNetworkSmDeviceFieldsParams {
	var ()
	return &UpdateNetworkSmDeviceFieldsParams{
		HTTPClient: client,
	}
}

/*UpdateNetworkSmDeviceFieldsParams contains all the parameters to send to the API endpoint
for the update network sm device fields operation typically these are written to a http.Request
*/
type UpdateNetworkSmDeviceFieldsParams struct {

	/*NetworkID*/
	NetworkID string
	/*UpdateNetworkSmDeviceFields*/
	UpdateNetworkSmDeviceFields *models.UpdateNetworkSmDeviceFields

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update network sm device fields params
func (o *UpdateNetworkSmDeviceFieldsParams) WithTimeout(timeout time.Duration) *UpdateNetworkSmDeviceFieldsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update network sm device fields params
func (o *UpdateNetworkSmDeviceFieldsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update network sm device fields params
func (o *UpdateNetworkSmDeviceFieldsParams) WithContext(ctx context.Context) *UpdateNetworkSmDeviceFieldsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update network sm device fields params
func (o *UpdateNetworkSmDeviceFieldsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update network sm device fields params
func (o *UpdateNetworkSmDeviceFieldsParams) WithHTTPClient(client *http.Client) *UpdateNetworkSmDeviceFieldsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update network sm device fields params
func (o *UpdateNetworkSmDeviceFieldsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNetworkID adds the networkID to the update network sm device fields params
func (o *UpdateNetworkSmDeviceFieldsParams) WithNetworkID(networkID string) *UpdateNetworkSmDeviceFieldsParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the update network sm device fields params
func (o *UpdateNetworkSmDeviceFieldsParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WithUpdateNetworkSmDeviceFields adds the updateNetworkSmDeviceFields to the update network sm device fields params
func (o *UpdateNetworkSmDeviceFieldsParams) WithUpdateNetworkSmDeviceFields(updateNetworkSmDeviceFields *models.UpdateNetworkSmDeviceFields) *UpdateNetworkSmDeviceFieldsParams {
	o.SetUpdateNetworkSmDeviceFields(updateNetworkSmDeviceFields)
	return o
}

// SetUpdateNetworkSmDeviceFields adds the updateNetworkSmDeviceFields to the update network sm device fields params
func (o *UpdateNetworkSmDeviceFieldsParams) SetUpdateNetworkSmDeviceFields(updateNetworkSmDeviceFields *models.UpdateNetworkSmDeviceFields) {
	o.UpdateNetworkSmDeviceFields = updateNetworkSmDeviceFields
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateNetworkSmDeviceFieldsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param networkId
	if err := r.SetPathParam("networkId", o.NetworkID); err != nil {
		return err
	}

	if o.UpdateNetworkSmDeviceFields != nil {
		if err := r.SetBodyParam(o.UpdateNetworkSmDeviceFields); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
