// Code generated by go-swagger; DO NOT EDIT.

package m_x_v_p_n_firewall

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetOrganizationVpnFirewallRulesReader is a Reader for the GetOrganizationVpnFirewallRules structure.
type GetOrganizationVpnFirewallRulesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrganizationVpnFirewallRulesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOrganizationVpnFirewallRulesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetOrganizationVpnFirewallRulesOK creates a GetOrganizationVpnFirewallRulesOK with default headers values
func NewGetOrganizationVpnFirewallRulesOK() *GetOrganizationVpnFirewallRulesOK {
	return &GetOrganizationVpnFirewallRulesOK{}
}

/*GetOrganizationVpnFirewallRulesOK handles this case with default header values.

Successful operation
*/
type GetOrganizationVpnFirewallRulesOK struct {
	Payload interface{}
}

func (o *GetOrganizationVpnFirewallRulesOK) Error() string {
	return fmt.Sprintf("[GET /organizations/{organizationId}/vpnFirewallRules][%d] getOrganizationVpnFirewallRulesOK  %+v", 200, o.Payload)
}

func (o *GetOrganizationVpnFirewallRulesOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetOrganizationVpnFirewallRulesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
