// Code generated by go-swagger; DO NOT EDIT.

package action_batches

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateOrganizationActionBatchReader is a Reader for the UpdateOrganizationActionBatch structure.
type UpdateOrganizationActionBatchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateOrganizationActionBatchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateOrganizationActionBatchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateOrganizationActionBatchOK creates a UpdateOrganizationActionBatchOK with default headers values
func NewUpdateOrganizationActionBatchOK() *UpdateOrganizationActionBatchOK {
	return &UpdateOrganizationActionBatchOK{}
}

/*UpdateOrganizationActionBatchOK handles this case with default header values.

Successful operation
*/
type UpdateOrganizationActionBatchOK struct {
	Payload interface{}
}

func (o *UpdateOrganizationActionBatchOK) Error() string {
	return fmt.Sprintf("[PUT /organizations/{organizationId}/actionBatches/{actionBatchId}][%d] updateOrganizationActionBatchOK  %+v", 200, o.Payload)
}

func (o *UpdateOrganizationActionBatchOK) GetPayload() interface{} {
	return o.Payload
}

func (o *UpdateOrganizationActionBatchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
