// Code generated by go-swagger; DO NOT EDIT.

package m_x_cellular_firewall

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateNetworkCellularFirewallRulesReader is a Reader for the UpdateNetworkCellularFirewallRules structure.
type UpdateNetworkCellularFirewallRulesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateNetworkCellularFirewallRulesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateNetworkCellularFirewallRulesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateNetworkCellularFirewallRulesOK creates a UpdateNetworkCellularFirewallRulesOK with default headers values
func NewUpdateNetworkCellularFirewallRulesOK() *UpdateNetworkCellularFirewallRulesOK {
	return &UpdateNetworkCellularFirewallRulesOK{}
}

/*UpdateNetworkCellularFirewallRulesOK handles this case with default header values.

Successful operation
*/
type UpdateNetworkCellularFirewallRulesOK struct {
	Payload interface{}
}

func (o *UpdateNetworkCellularFirewallRulesOK) Error() string {
	return fmt.Sprintf("[PUT /networks/{networkId}/cellularFirewallRules][%d] updateNetworkCellularFirewallRulesOK  %+v", 200, o.Payload)
}

func (o *UpdateNetworkCellularFirewallRulesOK) GetPayload() interface{} {
	return o.Payload
}

func (o *UpdateNetworkCellularFirewallRulesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
