// Code generated by go-swagger; DO NOT EDIT.

package switch_port_schedules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cisco-sso/meraki-cli/models"
)

// NewCreateNetworkSwitchPortScheduleParams creates a new CreateNetworkSwitchPortScheduleParams object
// with the default values initialized.
func NewCreateNetworkSwitchPortScheduleParams() *CreateNetworkSwitchPortScheduleParams {
	var ()
	return &CreateNetworkSwitchPortScheduleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateNetworkSwitchPortScheduleParamsWithTimeout creates a new CreateNetworkSwitchPortScheduleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateNetworkSwitchPortScheduleParamsWithTimeout(timeout time.Duration) *CreateNetworkSwitchPortScheduleParams {
	var ()
	return &CreateNetworkSwitchPortScheduleParams{

		timeout: timeout,
	}
}

// NewCreateNetworkSwitchPortScheduleParamsWithContext creates a new CreateNetworkSwitchPortScheduleParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateNetworkSwitchPortScheduleParamsWithContext(ctx context.Context) *CreateNetworkSwitchPortScheduleParams {
	var ()
	return &CreateNetworkSwitchPortScheduleParams{

		Context: ctx,
	}
}

// NewCreateNetworkSwitchPortScheduleParamsWithHTTPClient creates a new CreateNetworkSwitchPortScheduleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateNetworkSwitchPortScheduleParamsWithHTTPClient(client *http.Client) *CreateNetworkSwitchPortScheduleParams {
	var ()
	return &CreateNetworkSwitchPortScheduleParams{
		HTTPClient: client,
	}
}

/*CreateNetworkSwitchPortScheduleParams contains all the parameters to send to the API endpoint
for the create network switch port schedule operation typically these are written to a http.Request
*/
type CreateNetworkSwitchPortScheduleParams struct {

	/*CreateNetworkSwitchPortSchedule*/
	CreateNetworkSwitchPortSchedule *models.CreateNetworkSwitchPortSchedule
	/*NetworkID*/
	NetworkID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create network switch port schedule params
func (o *CreateNetworkSwitchPortScheduleParams) WithTimeout(timeout time.Duration) *CreateNetworkSwitchPortScheduleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create network switch port schedule params
func (o *CreateNetworkSwitchPortScheduleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create network switch port schedule params
func (o *CreateNetworkSwitchPortScheduleParams) WithContext(ctx context.Context) *CreateNetworkSwitchPortScheduleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create network switch port schedule params
func (o *CreateNetworkSwitchPortScheduleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create network switch port schedule params
func (o *CreateNetworkSwitchPortScheduleParams) WithHTTPClient(client *http.Client) *CreateNetworkSwitchPortScheduleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create network switch port schedule params
func (o *CreateNetworkSwitchPortScheduleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCreateNetworkSwitchPortSchedule adds the createNetworkSwitchPortSchedule to the create network switch port schedule params
func (o *CreateNetworkSwitchPortScheduleParams) WithCreateNetworkSwitchPortSchedule(createNetworkSwitchPortSchedule *models.CreateNetworkSwitchPortSchedule) *CreateNetworkSwitchPortScheduleParams {
	o.SetCreateNetworkSwitchPortSchedule(createNetworkSwitchPortSchedule)
	return o
}

// SetCreateNetworkSwitchPortSchedule adds the createNetworkSwitchPortSchedule to the create network switch port schedule params
func (o *CreateNetworkSwitchPortScheduleParams) SetCreateNetworkSwitchPortSchedule(createNetworkSwitchPortSchedule *models.CreateNetworkSwitchPortSchedule) {
	o.CreateNetworkSwitchPortSchedule = createNetworkSwitchPortSchedule
}

// WithNetworkID adds the networkID to the create network switch port schedule params
func (o *CreateNetworkSwitchPortScheduleParams) WithNetworkID(networkID string) *CreateNetworkSwitchPortScheduleParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the create network switch port schedule params
func (o *CreateNetworkSwitchPortScheduleParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateNetworkSwitchPortScheduleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CreateNetworkSwitchPortSchedule != nil {
		if err := r.SetBodyParam(o.CreateNetworkSwitchPortSchedule); err != nil {
			return err
		}
	}

	// path param networkId
	if err := r.SetPathParam("networkId", o.NetworkID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
