// Code generated by go-swagger; DO NOT EDIT.

package m_x_1_many_n_a_t_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetNetworkOneToManyNatRulesReader is a Reader for the GetNetworkOneToManyNatRules structure.
type GetNetworkOneToManyNatRulesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNetworkOneToManyNatRulesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNetworkOneToManyNatRulesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetNetworkOneToManyNatRulesOK creates a GetNetworkOneToManyNatRulesOK with default headers values
func NewGetNetworkOneToManyNatRulesOK() *GetNetworkOneToManyNatRulesOK {
	return &GetNetworkOneToManyNatRulesOK{}
}

/*GetNetworkOneToManyNatRulesOK handles this case with default header values.

Successful operation
*/
type GetNetworkOneToManyNatRulesOK struct {
	Payload interface{}
}

func (o *GetNetworkOneToManyNatRulesOK) Error() string {
	return fmt.Sprintf("[GET /networks/{networkId}/oneToManyNatRules][%d] getNetworkOneToManyNatRulesOK  %+v", 200, o.Payload)
}

func (o *GetNetworkOneToManyNatRulesOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetNetworkOneToManyNatRulesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
