// Code generated by go-swagger; DO NOT EDIT.

package m_g_port_forwarding_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new m g port forwarding rules API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for m g port forwarding rules API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetDeviceCellularGatewaySettingsPortForwardingRules(params *GetDeviceCellularGatewaySettingsPortForwardingRulesParams, authInfo runtime.ClientAuthInfoWriter) (*GetDeviceCellularGatewaySettingsPortForwardingRulesOK, error)

	UpdateDeviceCellularGatewaySettingsPortForwardingRules(params *UpdateDeviceCellularGatewaySettingsPortForwardingRulesParams, authInfo runtime.ClientAuthInfoWriter) (*UpdateDeviceCellularGatewaySettingsPortForwardingRulesOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetDeviceCellularGatewaySettingsPortForwardingRules gets device cellular gateway settings port forwarding rules

  Returns the port forwarding rules for a single MG.
*/
func (a *Client) GetDeviceCellularGatewaySettingsPortForwardingRules(params *GetDeviceCellularGatewaySettingsPortForwardingRulesParams, authInfo runtime.ClientAuthInfoWriter) (*GetDeviceCellularGatewaySettingsPortForwardingRulesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetDeviceCellularGatewaySettingsPortForwardingRulesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getDeviceCellularGatewaySettingsPortForwardingRules",
		Method:             "GET",
		PathPattern:        "/devices/{serial}/cellularGateway/settings/portForwardingRules",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetDeviceCellularGatewaySettingsPortForwardingRulesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetDeviceCellularGatewaySettingsPortForwardingRulesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getDeviceCellularGatewaySettingsPortForwardingRules: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  UpdateDeviceCellularGatewaySettingsPortForwardingRules updates device cellular gateway settings port forwarding rules

  Updates the port forwarding rules for a single MG.
*/
func (a *Client) UpdateDeviceCellularGatewaySettingsPortForwardingRules(params *UpdateDeviceCellularGatewaySettingsPortForwardingRulesParams, authInfo runtime.ClientAuthInfoWriter) (*UpdateDeviceCellularGatewaySettingsPortForwardingRulesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateDeviceCellularGatewaySettingsPortForwardingRulesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "updateDeviceCellularGatewaySettingsPortForwardingRules",
		Method:             "PUT",
		PathPattern:        "/devices/{serial}/cellularGateway/settings/portForwardingRules",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &UpdateDeviceCellularGatewaySettingsPortForwardingRulesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateDeviceCellularGatewaySettingsPortForwardingRulesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for updateDeviceCellularGatewaySettingsPortForwardingRules: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
