// Code generated by go-swagger; DO NOT EDIT.

package group_policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetNetworkGroupPoliciesReader is a Reader for the GetNetworkGroupPolicies structure.
type GetNetworkGroupPoliciesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNetworkGroupPoliciesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNetworkGroupPoliciesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetNetworkGroupPoliciesOK creates a GetNetworkGroupPoliciesOK with default headers values
func NewGetNetworkGroupPoliciesOK() *GetNetworkGroupPoliciesOK {
	return &GetNetworkGroupPoliciesOK{}
}

/*GetNetworkGroupPoliciesOK handles this case with default header values.

Successful operation
*/
type GetNetworkGroupPoliciesOK struct {
	Payload interface{}
}

func (o *GetNetworkGroupPoliciesOK) Error() string {
	return fmt.Sprintf("[GET /networks/{networkId}/groupPolicies][%d] getNetworkGroupPoliciesOK  %+v", 200, o.Payload)
}

func (o *GetNetworkGroupPoliciesOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetNetworkGroupPoliciesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
