// Code generated by go-swagger; DO NOT EDIT.

package bluetooth_settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateDeviceWirelessBluetoothSettingsReader is a Reader for the UpdateDeviceWirelessBluetoothSettings structure.
type UpdateDeviceWirelessBluetoothSettingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateDeviceWirelessBluetoothSettingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateDeviceWirelessBluetoothSettingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateDeviceWirelessBluetoothSettingsOK creates a UpdateDeviceWirelessBluetoothSettingsOK with default headers values
func NewUpdateDeviceWirelessBluetoothSettingsOK() *UpdateDeviceWirelessBluetoothSettingsOK {
	return &UpdateDeviceWirelessBluetoothSettingsOK{}
}

/*UpdateDeviceWirelessBluetoothSettingsOK handles this case with default header values.

Successful operation
*/
type UpdateDeviceWirelessBluetoothSettingsOK struct {
	Payload interface{}
}

func (o *UpdateDeviceWirelessBluetoothSettingsOK) Error() string {
	return fmt.Sprintf("[PUT /devices/{serial}/wireless/bluetooth/settings][%d] updateDeviceWirelessBluetoothSettingsOK  %+v", 200, o.Payload)
}

func (o *UpdateDeviceWirelessBluetoothSettingsOK) GetPayload() interface{} {
	return o.Payload
}

func (o *UpdateDeviceWirelessBluetoothSettingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
