// Code generated by go-swagger; DO NOT EDIT.

package intrusion_settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetNetworkSecurityIntrusionSettingsReader is a Reader for the GetNetworkSecurityIntrusionSettings structure.
type GetNetworkSecurityIntrusionSettingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNetworkSecurityIntrusionSettingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNetworkSecurityIntrusionSettingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetNetworkSecurityIntrusionSettingsOK creates a GetNetworkSecurityIntrusionSettingsOK with default headers values
func NewGetNetworkSecurityIntrusionSettingsOK() *GetNetworkSecurityIntrusionSettingsOK {
	return &GetNetworkSecurityIntrusionSettingsOK{}
}

/*GetNetworkSecurityIntrusionSettingsOK handles this case with default header values.

Successful operation
*/
type GetNetworkSecurityIntrusionSettingsOK struct {
	Payload interface{}
}

func (o *GetNetworkSecurityIntrusionSettingsOK) Error() string {
	return fmt.Sprintf("[GET /networks/{networkId}/security/intrusionSettings][%d] getNetworkSecurityIntrusionSettingsOK  %+v", 200, o.Payload)
}

func (o *GetNetworkSecurityIntrusionSettingsOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetNetworkSecurityIntrusionSettingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
