// Code generated by go-swagger; DO NOT EDIT.

package switch_a_c_ls

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new switch a c ls API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for switch a c ls API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetNetworkSwitchAccessControlLists(params *GetNetworkSwitchAccessControlListsParams, authInfo runtime.ClientAuthInfoWriter) (*GetNetworkSwitchAccessControlListsOK, error)

	UpdateNetworkSwitchAccessControlLists(params *UpdateNetworkSwitchAccessControlListsParams, authInfo runtime.ClientAuthInfoWriter) (*UpdateNetworkSwitchAccessControlListsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetNetworkSwitchAccessControlLists gets network switch access control lists

  Return the access control lists for a MS network
*/
func (a *Client) GetNetworkSwitchAccessControlLists(params *GetNetworkSwitchAccessControlListsParams, authInfo runtime.ClientAuthInfoWriter) (*GetNetworkSwitchAccessControlListsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetNetworkSwitchAccessControlListsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getNetworkSwitchAccessControlLists",
		Method:             "GET",
		PathPattern:        "/networks/{networkId}/switch/accessControlLists",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetNetworkSwitchAccessControlListsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetNetworkSwitchAccessControlListsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getNetworkSwitchAccessControlLists: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  UpdateNetworkSwitchAccessControlLists updates network switch access control lists

  Update the access control lists for a MS network
*/
func (a *Client) UpdateNetworkSwitchAccessControlLists(params *UpdateNetworkSwitchAccessControlListsParams, authInfo runtime.ClientAuthInfoWriter) (*UpdateNetworkSwitchAccessControlListsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateNetworkSwitchAccessControlListsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "updateNetworkSwitchAccessControlLists",
		Method:             "PUT",
		PathPattern:        "/networks/{networkId}/switch/accessControlLists",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &UpdateNetworkSwitchAccessControlListsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateNetworkSwitchAccessControlListsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for updateNetworkSwitchAccessControlLists: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
