// Code generated by go-swagger; DO NOT EDIT.

package api_usage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetOrganizationAPIRequestsOverviewReader is a Reader for the GetOrganizationAPIRequestsOverview structure.
type GetOrganizationAPIRequestsOverviewReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrganizationAPIRequestsOverviewReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOrganizationAPIRequestsOverviewOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetOrganizationAPIRequestsOverviewOK creates a GetOrganizationAPIRequestsOverviewOK with default headers values
func NewGetOrganizationAPIRequestsOverviewOK() *GetOrganizationAPIRequestsOverviewOK {
	return &GetOrganizationAPIRequestsOverviewOK{}
}

/*GetOrganizationAPIRequestsOverviewOK handles this case with default header values.

Successful operation
*/
type GetOrganizationAPIRequestsOverviewOK struct {
	Payload interface{}
}

func (o *GetOrganizationAPIRequestsOverviewOK) Error() string {
	return fmt.Sprintf("[GET /organizations/{organizationId}/apiRequests/overview][%d] getOrganizationApiRequestsOverviewOK  %+v", 200, o.Payload)
}

func (o *GetOrganizationAPIRequestsOverviewOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetOrganizationAPIRequestsOverviewOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
