// Code generated by go-swagger; DO NOT EDIT.

package m_x_1_1_n_a_t_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new m x 1 1 n a t rules API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for m x 1 1 n a t rules API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetNetworkOneToOneNatRules(params *GetNetworkOneToOneNatRulesParams, authInfo runtime.ClientAuthInfoWriter) (*GetNetworkOneToOneNatRulesOK, error)

	UpdateNetworkOneToOneNatRules(params *UpdateNetworkOneToOneNatRulesParams, authInfo runtime.ClientAuthInfoWriter) (*UpdateNetworkOneToOneNatRulesOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetNetworkOneToOneNatRules gets network one to one nat rules

  Return the 1:1 NAT mapping rules for an MX network
*/
func (a *Client) GetNetworkOneToOneNatRules(params *GetNetworkOneToOneNatRulesParams, authInfo runtime.ClientAuthInfoWriter) (*GetNetworkOneToOneNatRulesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetNetworkOneToOneNatRulesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getNetworkOneToOneNatRules",
		Method:             "GET",
		PathPattern:        "/networks/{networkId}/oneToOneNatRules",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetNetworkOneToOneNatRulesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetNetworkOneToOneNatRulesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getNetworkOneToOneNatRules: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  UpdateNetworkOneToOneNatRules updates network one to one nat rules

  Set the 1:1 NAT mapping rules for an MX network
*/
func (a *Client) UpdateNetworkOneToOneNatRules(params *UpdateNetworkOneToOneNatRulesParams, authInfo runtime.ClientAuthInfoWriter) (*UpdateNetworkOneToOneNatRulesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateNetworkOneToOneNatRulesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "updateNetworkOneToOneNatRules",
		Method:             "PUT",
		PathPattern:        "/networks/{networkId}/oneToOneNatRules",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &UpdateNetworkOneToOneNatRulesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateNetworkOneToOneNatRulesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for updateNetworkOneToOneNatRules: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
