// Code generated by go-swagger; DO NOT EDIT.

package m_x_1_1_n_a_t_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateNetworkOneToOneNatRulesReader is a Reader for the UpdateNetworkOneToOneNatRules structure.
type UpdateNetworkOneToOneNatRulesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateNetworkOneToOneNatRulesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateNetworkOneToOneNatRulesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateNetworkOneToOneNatRulesOK creates a UpdateNetworkOneToOneNatRulesOK with default headers values
func NewUpdateNetworkOneToOneNatRulesOK() *UpdateNetworkOneToOneNatRulesOK {
	return &UpdateNetworkOneToOneNatRulesOK{}
}

/*UpdateNetworkOneToOneNatRulesOK handles this case with default header values.

Successful operation
*/
type UpdateNetworkOneToOneNatRulesOK struct {
	Payload interface{}
}

func (o *UpdateNetworkOneToOneNatRulesOK) Error() string {
	return fmt.Sprintf("[PUT /networks/{networkId}/oneToOneNatRules][%d] updateNetworkOneToOneNatRulesOK  %+v", 200, o.Payload)
}

func (o *UpdateNetworkOneToOneNatRulesOK) GetPayload() interface{} {
	return o.Payload
}

func (o *UpdateNetworkOneToOneNatRulesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
