// Code generated by go-swagger; DO NOT EDIT.

package s_n_m_p_settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateNetworkSnmpSettingsReader is a Reader for the UpdateNetworkSnmpSettings structure.
type UpdateNetworkSnmpSettingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateNetworkSnmpSettingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateNetworkSnmpSettingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateNetworkSnmpSettingsOK creates a UpdateNetworkSnmpSettingsOK with default headers values
func NewUpdateNetworkSnmpSettingsOK() *UpdateNetworkSnmpSettingsOK {
	return &UpdateNetworkSnmpSettingsOK{}
}

/*UpdateNetworkSnmpSettingsOK handles this case with default header values.

Successful operation
*/
type UpdateNetworkSnmpSettingsOK struct {
	Payload interface{}
}

func (o *UpdateNetworkSnmpSettingsOK) Error() string {
	return fmt.Sprintf("[PUT /networks/{networkId}/snmpSettings][%d] updateNetworkSnmpSettingsOK  %+v", 200, o.Payload)
}

func (o *UpdateNetworkSnmpSettingsOK) GetPayload() interface{} {
	return o.Payload
}

func (o *UpdateNetworkSnmpSettingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
