// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// APIDocsSubtab ApiDocsSubtab
//
// The 'Help -> API docs' subtab where a detailed description of the Dashboard API is listed. Can be one of
//     'default or inherit', 'hide' or 'show'.
//
// swagger:model ApiDocsSubtab
type APIDocsSubtab string

const (

	// APIDocsSubtabDefaultOrInherit captures enum value "default or inherit"
	APIDocsSubtabDefaultOrInherit APIDocsSubtab = "default or inherit"

	// APIDocsSubtabHide captures enum value "hide"
	APIDocsSubtabHide APIDocsSubtab = "hide"

	// APIDocsSubtabShow captures enum value "show"
	APIDocsSubtabShow APIDocsSubtab = "show"
)

// for schema
var apiDocsSubtabEnum []interface{}

func init() {
	var res []APIDocsSubtab
	if err := json.Unmarshal([]byte(`["default or inherit","hide","show"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		apiDocsSubtabEnum = append(apiDocsSubtabEnum, v)
	}
}

func (m APIDocsSubtab) validateAPIDocsSubtabEnum(path, location string, value APIDocsSubtab) error {
	if err := validate.Enum(path, location, value, apiDocsSubtabEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this Api docs subtab
func (m APIDocsSubtab) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateAPIDocsSubtabEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
