// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ContentFiltering ContentFiltering
//
// The content filtering settings for your group policy
//
// swagger:model ContentFiltering
type ContentFiltering struct {

	// allowed Url patterns
	AllowedURLPatterns *AllowedURLPatterns `json:"allowedUrlPatterns,omitempty"`

	// blocked Url categories
	BlockedURLCategories *BlockedURLCategories `json:"blockedUrlCategories,omitempty"`

	// blocked Url patterns
	BlockedURLPatterns *BlockedURLPatterns `json:"blockedUrlPatterns,omitempty"`
}

// Validate validates this content filtering
func (m *ContentFiltering) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAllowedURLPatterns(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBlockedURLCategories(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBlockedURLPatterns(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ContentFiltering) validateAllowedURLPatterns(formats strfmt.Registry) error {

	if swag.IsZero(m.AllowedURLPatterns) { // not required
		return nil
	}

	if m.AllowedURLPatterns != nil {
		if err := m.AllowedURLPatterns.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("allowedUrlPatterns")
			}
			return err
		}
	}

	return nil
}

func (m *ContentFiltering) validateBlockedURLCategories(formats strfmt.Registry) error {

	if swag.IsZero(m.BlockedURLCategories) { // not required
		return nil
	}

	if m.BlockedURLCategories != nil {
		if err := m.BlockedURLCategories.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("blockedUrlCategories")
			}
			return err
		}
	}

	return nil
}

func (m *ContentFiltering) validateBlockedURLPatterns(formats strfmt.Registry) error {

	if swag.IsZero(m.BlockedURLPatterns) { // not required
		return nil
	}

	if m.BlockedURLPatterns != nil {
		if err := m.BlockedURLPatterns.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("blockedUrlPatterns")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ContentFiltering) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContentFiltering) UnmarshalBinary(b []byte) error {
	var res ContentFiltering
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
