// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CycleDeviceSwitchPorts cycleDeviceSwitchPorts
//
// swagger:model cycleDeviceSwitchPorts
type CycleDeviceSwitchPorts struct {

	// List of switch ports. Example: [1, 2-5, 1_MA-MOD-8X10G_1, 1_MA-MOD-8X10G_2-1_MA-MOD-8X10G_8]
	// Required: true
	Ports []string `json:"ports"`
}

// Validate validates this cycle device switch ports
func (m *CycleDeviceSwitchPorts) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePorts(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CycleDeviceSwitchPorts) validatePorts(formats strfmt.Registry) error {

	if err := validate.Required("ports", "body", m.Ports); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CycleDeviceSwitchPorts) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CycleDeviceSwitchPorts) UnmarshalBinary(b []byte) error {
	var res CycleDeviceSwitchPorts
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
