// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// DataProtectionRequestsSubtab DataProtectionRequestsSubtab
//
// The 'Help -> Data protection requests' Dashboard subtab on which requests to delete, restrict, or export end-user data can
//     be audited. Can be one of 'default or inherit', 'hide' or 'show'.
//
// swagger:model DataProtectionRequestsSubtab
type DataProtectionRequestsSubtab string

const (

	// DataProtectionRequestsSubtabDefaultOrInherit captures enum value "default or inherit"
	DataProtectionRequestsSubtabDefaultOrInherit DataProtectionRequestsSubtab = "default or inherit"

	// DataProtectionRequestsSubtabHide captures enum value "hide"
	DataProtectionRequestsSubtabHide DataProtectionRequestsSubtab = "hide"

	// DataProtectionRequestsSubtabShow captures enum value "show"
	DataProtectionRequestsSubtabShow DataProtectionRequestsSubtab = "show"
)

// for schema
var dataProtectionRequestsSubtabEnum []interface{}

func init() {
	var res []DataProtectionRequestsSubtab
	if err := json.Unmarshal([]byte(`["default or inherit","hide","show"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		dataProtectionRequestsSubtabEnum = append(dataProtectionRequestsSubtabEnum, v)
	}
}

func (m DataProtectionRequestsSubtab) validateDataProtectionRequestsSubtabEnum(path, location string, value DataProtectionRequestsSubtab) error {
	if err := validate.Enum(path, location, value, dataProtectionRequestsSubtabEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this data protection requests subtab
func (m DataProtectionRequestsSubtab) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateDataProtectionRequestsSubtabEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
