// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Hub Hub
//
// swagger:model Hub
type Hub struct {

	// The network ID of the hub.
	// Required: true
	HubID *string `json:"hubId"`

	// Only valid in 'spoke' mode. Indicates whether default route traffic should be sent to this hub.
	UseDefaultRoute bool `json:"useDefaultRoute,omitempty"`
}

// Validate validates this hub
func (m *Hub) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHubID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Hub) validateHubID(formats strfmt.Registry) error {

	if err := validate.Required("hubId", "body", m.HubID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Hub) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Hub) UnmarshalBinary(b []byte) error {
	var res Hub
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
