// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MV12WE MV12WE
//
// Quality and resolution for MV12WE camera models.
//
// swagger:model MV12WE
type MV12WE struct {

	// quality
	// Required: true
	Quality Quality1 `json:"quality"`

	// resolution
	// Required: true
	Resolution Resolution1 `json:"resolution"`
}

// Validate validates this m v12 w e
func (m *MV12WE) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateQuality(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResolution(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MV12WE) validateQuality(formats strfmt.Registry) error {

	if err := m.Quality.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("quality")
		}
		return err
	}

	return nil
}

func (m *MV12WE) validateResolution(formats strfmt.Registry) error {

	if err := m.Resolution.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("resolution")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MV12WE) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MV12WE) UnmarshalBinary(b []byte) error {
	var res MV12WE
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
