// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MV22XMV72X MV22XMV72X
//
// Quality and resolution for MV22X/MV72X camera models.
//
// swagger:model MV22XMV72X
type MV22XMV72X struct {

	// quality
	// Required: true
	Quality Quality1 `json:"quality"`

	// resolution
	// Required: true
	Resolution Resolution4 `json:"resolution"`
}

// Validate validates this m v22 x m v72 x
func (m *MV22XMV72X) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateQuality(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResolution(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MV22XMV72X) validateQuality(formats strfmt.Registry) error {

	if err := m.Quality.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("quality")
		}
		return err
	}

	return nil
}

func (m *MV22XMV72X) validateResolution(formats strfmt.Registry) error {

	if err := m.Resolution.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("resolution")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MV22XMV72X) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MV22XMV72X) UnmarshalBinary(b []byte) error {
	var res MV22XMV72X
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
