// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Network2 Network2
//
// swagger:model Network2
type Network2 struct {

	// The privilege of the SAML administrator on the network
	Access string `json:"access,omitempty"`

	// The network ID
	ID string `json:"id,omitempty"`
}

// Validate validates this network2
func (m *Network2) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Network2) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Network2) UnmarshalBinary(b []byte) error {
	var res Network2
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
