// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// Policy7 Policy7
//
// 'allow' or 'deny' traffic specified by this rule.
//
// swagger:model Policy7
type Policy7 string

const (

	// Policy7Allow captures enum value "allow"
	Policy7Allow Policy7 = "allow"

	// Policy7Deny captures enum value "deny"
	Policy7Deny Policy7 = "deny"
)

// for schema
var policy7Enum []interface{}

func init() {
	var res []Policy7
	if err := json.Unmarshal([]byte(`["allow","deny"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		policy7Enum = append(policy7Enum, v)
	}
}

func (m Policy7) validatePolicy7Enum(path, location string, value Policy7) error {
	if err := validate.Enum(path, location, value, policy7Enum); err != nil {
		return err
	}
	return nil
}

// Validate validates this policy7
func (m Policy7) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validatePolicy7Enum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
