// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// SplashPage SplashPage
//
// The type of splash page for the SSID ('None', 'Click-through splash page', 'Billing', 'Password-protected with Meraki RADIUS', 'Password-protected with custom RADIUS', 'Password-protected with Active Directory', 'Password-protected with LDAP', 'SMS authentication', 'Systems Manager Sentry', 'Facebook Wi-Fi', 'Google OAuth' or 'Sponsored guest'). This attribute is not supported for template children.
//
// swagger:model SplashPage
type SplashPage string

const (

	// SplashPageNone captures enum value "None"
	SplashPageNone SplashPage = "None"

	// SplashPageClickThroughSplashPage captures enum value "Click-through splash page"
	SplashPageClickThroughSplashPage SplashPage = "Click-through splash page"

	// SplashPageBilling captures enum value "Billing"
	SplashPageBilling SplashPage = "Billing"

	// SplashPagePasswordProtectedWithMerakiRADIUS captures enum value "Password-protected with Meraki RADIUS"
	SplashPagePasswordProtectedWithMerakiRADIUS SplashPage = "Password-protected with Meraki RADIUS"

	// SplashPagePasswordProtectedWithCustomRADIUS captures enum value "Password-protected with custom RADIUS"
	SplashPagePasswordProtectedWithCustomRADIUS SplashPage = "Password-protected with custom RADIUS"

	// SplashPagePasswordProtectedWithActiveDirectory captures enum value "Password-protected with Active Directory"
	SplashPagePasswordProtectedWithActiveDirectory SplashPage = "Password-protected with Active Directory"

	// SplashPagePasswordProtectedWithLDAP captures enum value "Password-protected with LDAP"
	SplashPagePasswordProtectedWithLDAP SplashPage = "Password-protected with LDAP"

	// SplashPageSMSAuthentication captures enum value "SMS authentication"
	SplashPageSMSAuthentication SplashPage = "SMS authentication"

	// SplashPageSystemsManagerSentry captures enum value "Systems Manager Sentry"
	SplashPageSystemsManagerSentry SplashPage = "Systems Manager Sentry"

	// SplashPageFacebookWiFi captures enum value "Facebook Wi-Fi"
	SplashPageFacebookWiFi SplashPage = "Facebook Wi-Fi"

	// SplashPageGoogleOAuth captures enum value "Google OAuth"
	SplashPageGoogleOAuth SplashPage = "Google OAuth"

	// SplashPageSponsoredGuest captures enum value "Sponsored guest"
	SplashPageSponsoredGuest SplashPage = "Sponsored guest"
)

// for schema
var splashPageEnum []interface{}

func init() {
	var res []SplashPage
	if err := json.Unmarshal([]byte(`["None","Click-through splash page","Billing","Password-protected with Meraki RADIUS","Password-protected with custom RADIUS","Password-protected with Active Directory","Password-protected with LDAP","SMS authentication","Systems Manager Sentry","Facebook Wi-Fi","Google OAuth","Sponsored guest"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		splashPageEnum = append(splashPageEnum, v)
	}
}

func (m SplashPage) validateSplashPageEnum(path, location string, value SplashPage) error {
	if err := validate.Enum(path, location, value, splashPageEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this splash page
func (m SplashPage) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateSplashPageEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
