// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateNetworkAlertSettings updateNetworkAlertSettings
//
// swagger:model updateNetworkAlertSettings
type UpdateNetworkAlertSettings struct {

	// Alert-specific configuration for each type. Only alerts that pertain to the network can be updated.
	Alerts []*Alert `json:"alerts"`

	// default destinations
	DefaultDestinations *DefaultDestinations `json:"defaultDestinations,omitempty"`
}

// Validate validates this update network alert settings
func (m *UpdateNetworkAlertSettings) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAlerts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDefaultDestinations(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateNetworkAlertSettings) validateAlerts(formats strfmt.Registry) error {

	if swag.IsZero(m.Alerts) { // not required
		return nil
	}

	for i := 0; i < len(m.Alerts); i++ {
		if swag.IsZero(m.Alerts[i]) { // not required
			continue
		}

		if m.Alerts[i] != nil {
			if err := m.Alerts[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("alerts" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *UpdateNetworkAlertSettings) validateDefaultDestinations(formats strfmt.Registry) error {

	if swag.IsZero(m.DefaultDestinations) { // not required
		return nil
	}

	if m.DefaultDestinations != nil {
		if err := m.DefaultDestinations.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("defaultDestinations")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UpdateNetworkAlertSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateNetworkAlertSettings) UnmarshalBinary(b []byte) error {
	var res UpdateNetworkAlertSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
