// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateNetworkSmAppPolaris updateNetworkSmAppPolaris
//
// swagger:model updateNetworkSmAppPolaris
type UpdateNetworkSmAppPolaris struct {

	// optional: Whether or not SM should auto-install this app (one of true or false)
	PreventAutoInstall bool `json:"preventAutoInstall,omitempty"`

	// optional: The scope (one of all, none, automatic, withAny, withAll, withoutAny, or withoutAll) and a set of tags of the devices to be assigned
	Scope string `json:"scope,omitempty"`

	// optional: Whether or not the app should use VPP by device assignment (one of true or false)
	UsesVPP bool `json:"usesVPP,omitempty"`
}

// Validate validates this update network sm app polaris
func (m *UpdateNetworkSmAppPolaris) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateNetworkSmAppPolaris) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateNetworkSmAppPolaris) UnmarshalBinary(b []byte) error {
	var res UpdateNetworkSmAppPolaris
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
